### ISSUE TITLE
When using component in state, bindings which aren't defined in resolve gets a default value

### ISSUE THREAD

**Issue by gabguy** [ui-router/angular#100]
i have a component: `<example attr=""></example>`
I use it as a state and also as a standalone component, I want to pass it a function to 'attr' binding
when using it as a component. I do not want to pass it when using it as a state.
UI-router generates a default binding ($resolve.attr()) even if there is no key for attr in the resolve object.
This makes it hard to check inside the component if a function has been passed or not.
Please fix it so values that were not defined in the resolve object will just be undefined

**Comment by christopherthielen** [comment]
Was this issue supposed to be for UI-Router for AngularJS or for Angular?  The existence of `$resolve` in the bug report leads me to believe it belongs in http://github.com/angular-ui/ui-router/issues
