### ISSUE TITLE
Angular 4 Release

### ISSUE THREAD

**Issue by TitanNano** [ui-router/angular#101]
Could you make a angular 4 release? 
We really would need an ui-router version which is compatible with angular 4.

**Comment by christopherthielen** [comment]
Everything is ready. Hopefully today or tomorrow.

**Comment by ciel** [comment]
Really looking forward to it. The built in router just doesn't cut it.

**Comment by mkoczorowski** [comment]
+1

**Comment by stupidSheep** [comment]
Hi @christopherthielen Thanks a lot for beta6! :-)

**Comment by christopherthielen** [comment]
let me know if you have any issues with beta.6
