### ISSUE TITLE
help needed / hooks

### ISSUE THREAD

**Issue by mkoczorowski** [ui-router/angular#105]
Hi guys,

What is the correct way to inject a service to a onEnter hook ?  I would like to check for the user and if not logged in navigate somewehre else. In angular1 U used event.preventDefault() to stop navigation. and something along router.sync() to continue with navigation. What would be the correct way to achieve this in ng2 version.

Thank you for the help! great work

**Comment by mkoczorowski** [comment]
Solved

**Comment by VeeteshJain** [comment]
@mkoczorowski can you plz share your solution I had run into the same issue, maybe a code snippet would be helpful, thanks :-)

**Comment by mkoczorowski** [comment]
> @mkoczorowski can you plz share your solution I had run into the same issue, maybe a code snippet would be helpful, thanks :-)

This is actually quite easy. Make user the service is provided in providers or in root, then onEnter hook gives you transition. Just do transition->injector()->get(Service);
