### ISSUE TITLE
cannot use parent attrribute with lazy loaded states

### ISSUE THREAD

**Issue by mkoczorowski** [ui-router/angular#106]
The following configuration

![image](https://cloud.githubusercontent.com/assets/8155896/25629981/5e08de44-2f63-11e7-8b82-84519a8535eb.png)

causes an exception to be thrown ' Parent property should not have a '.' in their name.

**Comment by aitboudad** [comment]
Currently parent is not allowed in that case, you have to define it inside loaded module `StockreportModule`.

```ts
UIRouterModule.forRoot({
  { name: 'shr-report', parent: 'app' }
  ...
}),
```

**Comment by mkoczorowski** [comment]
thank you
