### ISSUE TITLE
Feature request: resolve and dynamic parameters

### ISSUE THREAD

**Issue by mkoczorowski** [ui-router/angular#107]
Since we can bind state resolves to @Input component properties, it would be nice to be able to declare a parameter as dynamic (so component is not destroyed each time) but then state 'resolve' should run on each parameter change. then we will be able to use OnChanges component hook with dynamic parameters.

How else I can react on changes inside of a component ? I cant see any way to act on dynamic parameter change

**Comment by eseliger** [comment]
I have the same question, how is it possible to react to changes of a dynamic parameter?

**Comment by christopherthielen** [comment]
I'm still considering how resolve + dynamic params can be implemented.  I learned today that `ngOnChanges` only works with bindings (template bindings, I assume).  When inputs are changed programmatically (like ui-router would have to do), then `ngOnChanges` callback is not run ([related bug](https://github.com/ui-router/angular/issues/174)).

To react to dynamic parameter changes, I recommend subscribing to the `router.globals.success$` observable in your component.  Here's an example: https://stackblitz.com/edit/ui-router-angular-hryke3?file=app%2Fgeneric.component.ts
