### ISSUE TITLE
RXWAIT observable$.cache is not a function

### ISSUE THREAD

**Issue by mkoczorowski** [ui-router/angular#108]
.cache is deprecated now. We should change this to .share() or publish().refCount(1)

**Comment by mkoczorowski** [comment]
I can fix this, if Im able to do a pull

**Comment by plcart** [comment]
Please consider this change as your next RC

**Comment by claudiuconstantin** [comment]
Any workaround for this?

**Comment by plcart** [comment]
get the operator/cache.(js|d.ts|map) file from "rxjs": "5.0.0-beta.12" and add to your app or to node_modules/rxjs/operator/ & node_modules/rxjs/add/operator/

**Comment by christopherthielen** [comment]
RXWAIT is not really working properly even with `.cache()`.  I think the ui-router team needs need to take a step back and re-evaluate how to implement RXWAIT

**Comment by DamianNurzynski** [comment]
I used `
                        policy: { async: "RXWAIT" }`

Console shows:
 `stateService.js:41 Transition Rejection($id: 0 type: 6, message: The transition errored, detail: TypeError: Cannot read property 'cache' of undefined)`

How to resolve this problem?  Its necessary to change node_modules folder?

**Comment by plcart** [comment]
Create a file with this content
`import { Observable } from 'rxjs/Observable';
import { Scheduler } from 'rxjs/Scheduler';
import { ReplaySubject } from 'rxjs/ReplaySubject';
import { Observer } from 'rxjs/Observer';
import { Subscription } from 'rxjs/Subscription';

export function cache<T>(
	bufferSize: number = Number.POSITIVE_INFINITY,
	windowTime: number = Number.POSITIVE_INFINITY,
	scheduler?: Scheduler): Observable<T> {
	let subject: ReplaySubject<T>;
	let source = this;
	let refs = 0;
	let outerSub: Subscription;

	const getSubject = () => {
		subject = new ReplaySubject<T>(bufferSize, windowTime, scheduler);
		return subject;
	};

	return new Observable<T>((observer: Observer<T>) => {
		if (!subject) {
			subject = getSubject();
			outerSub = source.subscribe(
				(value: T) => subject.next(value),
				(err: any) => {
					let s = subject;
					subject = null;
					s.error(err);
				},
				() => subject.complete()
			);
		}

		refs++;

		if (!subject) {
			subject = getSubject();
		}
		let innerSub = subject.subscribe(observer);

		return () => {
			refs--;
			if (innerSub) {
				innerSub.unsubscribe();
			}
			if (refs === 0) {
				outerSub.unsubscribe();
			}
		};
	});
}

export interface CacheSignature<T> {
	(bufferSize?: number, windowTime?: number, scheduler?: Scheduler): Observable<T>;
}`

at some main location in your app

`import { cache, CacheSignature } from '../services/cache';

Observable.prototype.cache = cache;

declare module 'rxjs/Observable' {
	interface Observable<T> {
		cache: CacheSignature<T>;
	}
}`

**Comment by kuhnroyal** [comment]
This is somewhat of a blocker, I think `.shareReplay()` could potentially solve this problem.
It is available in rxjs 5.4.0+

https://github.com/ReactiveX/rxjs/pull/2443
https://github.com/ReactiveX/rxjs/blob/892700dd4f5d5e5f9ae9276ede32208f4390c5e9/CHANGELOG.md#540-2017-05-09

**Comment by mkoczorowski** [comment]
this issue is in beta.10 milestone.. but rc was released after bata.9 ?

**Comment by kuhnroyal** [comment]
I tried to fix this in core but this is not possible, the rxjs typings/imports are needed to get this working.

I think the `ResolvePolicy` needs to become pluggable. Core should only provide `WAIT` and `NOWAIT` by default.
After this the whole `RXWAIT` can easily be implemented in the ng2/react module with the correct typings and plugged in.

At the moment I doubt anyone is using `RXWAIT` because it simply doesn't work with any recent version of angular and rxjs 5+.

So I propose `RXWAIT` gets dropped from core and implemented in ng2/react. Not sure how this can fit in the ng1 module.

@christopherthielen What do you think, is this possible?

**Comment by colmben** [comment]
Am I missing something or is this not a pretty major showstopper for an Angular 2+ router? Observables are all over the place in Angular now. Is the suggested workaround just to "toPromise" everything?

**Comment by colmben** [comment]
Also, its been around for nearly a year, can we take RXWAIT out of the docs?

**Comment by vincentdewisme** [comment]
Got the same error in my project:
`TypeError: observable$.cache is not a function
    at waitForRx (resolvable.js:83)`

Solved it by promisifying all my Observables...
So sad the other workaround creating the cache method on Observable did not work.
