### ISSUE TITLE
resolvePoclicy: {async: 'NOWAIT'} errors with function not found

### ISSUE THREAD

**Issue by mkoczorowski** [ui-router/angular#110]
resolvePoslicy: {async: 'NOWAIT'}

above errors with 'this.native.get is not a function'

![image](https://cloud.githubusercontent.com/assets/8155896/25745683/053463a6-3198-11e7-8cfb-94b19843d060.png)

**Comment by aitboudad** [comment]
I can reproduce your issue and I'm not sure if it's related to the resolve policy.
By the way `NOWAIT` currently not supported yet see https://github.com/ui-router/angular/pull/67

***Note***: `resolvePoclicy` is not the right property it should be `policy`.
