### ISSUE TITLE
feature: allow to render components beside to ui-view

### ISSUE THREAD

**Issue by welond** [ui-router/angular#112]
It would be great if ui-view render components beside, it will remove level of nesting

**Comment by christopherthielen** [comment]
I prefer nesting inside the ui-view, but I see your point.  This could be configurable as a global default, and per-ui-view using an attribute.

**Comment by shyamal890** [comment]
Currently `ng-component` inside the `ui-view` div is breaking css

**Comment by shyamal890** [comment]
@christopherthielen can you please share an update on this?
