### ISSUE TITLE
help needed. lazy module with two urls

### ISSUE THREAD

**Issue by mkoczorowski** [ui-router/angular#117]
Guys,
I need some help. I have a lazy loaded module which needs to be accessed by two urls declared as so:
```
  { name: 'app.directory.**', url: '/share-prices', loadChildren: 'app/+modules/directory/directory.module#DirectoryModule'},
  { name: 'app.directory.**', url: '/index-prices', loadChildren: 'app/+modules/directory/directory.module#DirectoryModule'},

```

then the lazy loaded routes look like;
```
{
    name     : 'app.directory',
    component: DirectoryComponent
  },

  {
    name     : 'shares',
    url      : '/share-prices?page&regions',
    parent   : 'app.directory',
    component: SecuritiesComponent,
    resolve  : [
      { provide: 'view', deps: [SecurityService, Transition], useFactory: directorySharesResolve }
    ],
    params: {
      type: 'shr',
      page: {
        dynamic: true
      }
    }
  },
  {
    name     : 'indices',
    url      : '/index-prices',
    parent   : 'app.directory',
    component: SecuritiesComponent,
    resolve  : [
      { provide: 'view', deps: [SecurityService, Transition], useFactory: directorySharesResolve }
    ],
    params: {
      type: 'idx'
    }
  }
```

problem is that having the above declaration in the root state declarations throws an exception
```
Error: State 'app.directory.**' is already defined
```

Is there any other way to achieve this so it actually works ?

**Comment by mkoczorowski** [comment]
If I try to add all of the routes to root state declarations (skip the .**) bit. app wont compile as I aslo have to add lazy modules to the app and there is no lazy loading anymore.

**Comment by lyslim** [comment]
Guess the lazy loaded module states should be added to root state, while the other 3 states should be added to corresponding module states

**Comment by aitboudad** [comment]
Try with
```ts
  { name: 'app.directory.shares.**', url: '/share-prices', loadChildren: ...},
  { name: 'app.directory.indices.**', url: '/index-prices', loadChildren: ...},
```
or 
```ts
  { name: 'app.directory.**', url: '/(share-prices|index-prices)', loadChildren: ...},
```

**Comment by mkoczorowski** [comment]
Wow, thanks a lot @aitboudad! One more issue I'm struggling with, Is there a way to predefine all of the states during the boot of the application but lazy load the modules? Defining states in this way 
``` name: 'app.directory.**', url: '/(share-prices|index-prices)', loadChildren: ...},```
and adding states after lazy load, works fine but the links generated for all of the children are incorrect if a module has not been loaded yet.

**Comment by aitboudad** [comment]
nop but it would be nice to have, something like:
```ts
{ 
    name: 'app.directory.**', 
    url: '/(share-prices|index-prices)', 
    loadChildren: ...
    childrenUrls: [
        { name: 'shares', url: '/share-prices?page&regions', }
        ...
    ]
},
```
right now you have to define them separatly, did you tried with:
```ts
  { name: 'shares.**', url: '/share-prices', loadChildren: ...},
  { name: 'indices.**', url: '/index-prices', loadChildren: ...},
```

**Comment by mkoczorowski** [comment]
yes, thats what I have atm, but href attributes are incorrect when a lazy module is not loaded.
for example in a shares module shares.** defines its children as shares.one (/shares/one) and shares.one.a (/shares/one/a) its impossible to create a href link to shares.one.a neither using service nor in html. shares.one.a is only declared in a lazy module, so proper href attributes only appear when this module is loaded. Its impossible to do a site map for example, or have a proper href link to  a deep module substate, without loading the module first.

**Comment by mkoczorowski** [comment]
@aitboudad the following 
```
 { name: 'app.directory.**', url: '/(share-prices|index-prices)', loadChildren: ...},
```
doesnt seem to be working :-( .. this bit -> (share-prices|index-prices)
is there any other solution ?

**Comment by aitboudad** [comment]
@mkoczorowski `url: '/{subpath:share-prices|index-prices}'` (https://github.com/ui-router/core/issues/28#issuecomment-272759255)

**Comment by mkoczorowski** [comment]
this worked! well done, awesome work! @aitboudad @christopherthielen. Closing the issue
