### ISSUE TITLE
uiSrefActive and abstract state

### ISSUE THREAD

**Issue by maxkorz** [ui-router/angular#131]
Hi. In Angular 1 I could do this:
```
<ul>
    <li ui-sref-active="{'active': 'dashboard'}">
        <a ui-sref="dashboard.index">
            <i class="mdi mdi-view-dashboard"></i> Dashboard
        </a>
    </li>
    <li ui-sref-active="{'active': 'admin'}">
        <a ui-sref="admin.index">
            <i class="mdi mdi-account"></i> Admin Panel
        </a>
    </li>
....
```
**dashboard** is an abstract state with a lot of nested states. I want to add the "active" class to menu item if any of those states are active.

docs https://ui-router.github.io/ng1/docs/latest/modules/directives.html#glob-mode

I don't see such feature in Angular 2 docs https://ui-router.github.io/ng2/docs/latest/classes/directives.uisrefactive.html

How do I add class "active" in this case?

**Comment by christopherthielen** [comment]
Angular 2 version doesn't have exactly that feature.  

You can use an invisible `uiSref` to the parent state inside a `uiSrefActive`: https://stackblitz.com/edit/ui-router-angular-ubklxb?file=app/app.component.ts.

Note `display: none`
```html
     <li uiSrefActive="active">
        <span uiSref="home" style="display: none"></span>
        <span>Some Home State is active</span>
      </li>
```

Sometimes you'll have links to ALL the substates inside some parent element.  You want the parent element to have the 'active' class when any substate is active.  If a `uiSrefActive` encloses multiple `uiSref`, any of the linked states will toggle the 'active' state.

https://stackblitz.com/edit/ui-router-angular-fydrss?file=app%2Fapp.component.ts

```html
    <ul uiSrefActiveEq="active">
      <li><a uiSref="home">Home</a></li>
      <li><a uiSref="home.index">Home.index</a></li>
      <li><a uiSref="home.other">Home.other</a></li>
    </ul>
```

Sorry about the long delay for an answer.  Hope this is helpful.
