### ISSUE TITLE
StateService.go reloads state even with {reload: false}

### ISSUE THREAD

**Issue by wjbLabs** [ui-router/angular#133]
I am using https://github.com/ngx-translate/core to translate pages that always has ``/locale`` prefix:
```ts
export let STATES: Ng2StateDeclaration[] = [
    {
        name: 'root',
        url: '/:locale',
        abstract: true,
        views: {            
           'navigation@root': RootNavigationComponent, // other views cut for brevity
        },
        resolve: [
            {
                token: 'locale', // not injected but only used to configure TranslateService::use()
                deps: [Transition, TranslateService],
                resolveFn: localeResolver,
            },
        ],
    },
];
```

and component itself, relevant code only:
```ts
export class RootNavigationComponent {
    changeLocale(locale) {
        this.translateService.use(locale);
        this.stateService.go('.', {'locale': locale}, {reload: false});
    }
}
```

First line works and changes translations but URL keeps same prefix (for example ``site.com/en/profile``). When you change locale, I would also like to change URL to ``site.com/es/profile`` for nice UX. Also, google can index these pages as well.

But even with ``reload: false``, all states are reloaded which brakes radio streaming and chat I am making. Even with (internal) ``notify: false`` doesn't change that.

How can I do this?

**Comment by mkoczorowski** [comment]
you have to declare this param as dynamic
https://ui-router.github.io/ng2/docs/latest/interfaces/params.paramtypedefinition.html#dynamic

**Comment by wjbLabs** [comment]
Thank you @mkoczorowski , that is absolutely amazing!
