### ISSUE TITLE
Angular 4 + Universal: Window is not defined

### ISSUE THREAD

**Issue by mchambaud** [ui-router/angular#134]
Everything works fine using `ng serve` and it compiles fine with `ngc` but I get the following exception at runtime.

```
ReferenceError: window is not defined
    at Ng2LocationServices.BaseLocationServices (/Users/Michael/Documents/my-app/node_modules/@uirouter/core/lib/vanilla/baseLocationService.js:20:26)
    at new Ng2LocationServices (/Users/Michael/Documents/my-app/dist/out-tsc/src/server.js:3923:28)
    at uiRouterFactory (/Users/Michael/Documents/my-app/dist/out-tsc/src/server.js:2656:30)
    at _callFactory (/Users/Michael/Documents/my-app/node_modules/@angular/core/bundles/core.umd.js:9650:34)
    at _createProviderInstance$1 (/Users/Michael/Documents/my-app/node_modules/@angular/core/bundles/core.umd.js:9579:26)
    at initNgModule (/Users/Michael/Documents/my-app/node_modules/@angular/core/bundles/core.umd.js:9530:13)
    at new NgModuleRef_ (/Users/Michael/Documents/my-app/node_modules/@angular/core/bundles/core.umd.js:10638:9)
    at Object.createNgModuleRef (/Users/Michael/Documents/my-app/node_modules/@angular/core/bundles/core.umd.js:10622:12)
    at NgModuleFactory_.create (/Users/Michael/Documents/my-app/node_modules/@angular/core/bundles/core.umd.js:13901:25)
    at /Users/Michael/Documents/my-app/node_modules/@angular/core/bundles/core.umd.js:4588:61
    at ZoneDelegate.invoke (/Users/Michael/Documents/my-app/node_modules/zone.js/dist/zone-node.js:365:26)
    at Object.onInvoke (/Users/Michael/Documents/my-app/node_modules/@angular/core/bundles/core.umd.js:3965:37)
    at ZoneDelegate.invoke (/Users/Michael/Documents/my-app/node_modules/zone.js/dist/zone-node.js:364:32)
    at Zone.run (/Users/Michael/Documents/my-app/node_modules/zone.js/dist/zone-node.js:125:43)
    at NgZone.run (/Users/Michael/Documents/my-app/node_modules/@angular/core/bundles/core.umd.js:3833:62)
```

this is my **app.server.module.ts**

```
import { NgModule } from '@angular/core';
import { ServerModule } from '@angular/platform-server';
import { BrowserModule } from '@angular/platform-browser';
import { AppModule } from './app.module';
import { AppComponent } from './app.component';
import { LocationStrategy } from '@angular/common';
import { UIRouter, MemoryLocationConfig, MemoryLocationService } from '@uirouter/angular';

@NgModule({
    imports: [
        BrowserModule.withServerTransition({ appId: 'my-app' }),
        ServerModule,
        AppModule
    ],
    bootstrap: [AppComponent]
})

export class AppServerModule {
    constructor(router: UIRouter, locationStrategy: LocationStrategy) {
        router.locationConfig = new MemoryLocationConfig();
        router.locationService = new MemoryLocationService(router);
        router.locationService['_url'] = locationStrategy.path(true);
    }
}
```

Did what #43 said to do but no luck.

**Comment by aitboudad** [comment]
Universal support is in progress (just a few little tweaks remain)
if you use webpack you can make it work by overriding window & location variable.

**Comment by mchambaud** [comment]
What would be the best way to achieve this?

**Comment by aitboudad** [comment]
Right now I'm using `DefinePlugin`:

```ts
new DefinePlugin({
    window: undefined,
    document: undefined,
    location: JSON.stringify({
        protocol: 'https', // `http` or `https`
        host: `your host`,
    })
}),
```

**Comment by mchambaud** [comment]
So I'm using `angular-cli` and I have a `webpack.config` for some server stuff which is where I've put this but it does not seem to work...

**Comment by aitboudad** [comment]
@mchambaud which version of `uirouter` do you use ?

**Comment by mchambaud** [comment]
1.0.0-beta.7

**Comment by aitboudad** [comment]
you should remove `@uirouter/angular` in externals entry

**Comment by mchambaud** [comment]
`ngc` exploses without it

**Comment by aitboudad** [comment]
can you use my repo to check if it's work in your project

```package.json
"@uirouter/angular": "https://github.com/aitboudad/ng2#f8201c2c368baa759b32e392a1308fc26e09a176",
```

instead of:
```ts 
import {} from @uirouter/angular
``` 
use:
```ts
import {} from @uirouter/angular/src
```

**Comment by mchambaud** [comment]
Ok wil do

**Comment by mchambaud** [comment]
I get error with the imports to `@uirouter/angular/src` can't resolve

**Comment by aitboudad** [comment]
you should target the folder `node_modules/@uirouter/angular/src` which contains the ts files (check if exist firstly).
I think we don't use the same tools, I'll try to provide you a working example in a separate repo in weekend.

**Comment by mchambaud** [comment]
When I `npm install` your package there is no `src` folder :\

**Comment by aitboudad** [comment]
can you update package hash and try again

```package.json
"@uirouter/angular": "https://github.com/aitboudad/ng2#a7e3387a7a821c105ce6e8538657d4cd161ed881",
```

**Comment by mchambaud** [comment]
So! It compiles!

But I get window is not defined at runtime..

**Comment by mchambaud** [comment]
My skype is the same as my GitHub username

**Comment by mchambaud** [comment]
Maybe I can help finish @uirouter for Universal. What pending tasks is there?

**Comment by aitboudad** [comment]
you can start by https://github.com/ui-router/core/blob/master/src/vanilla/baseLocationService.ts#L16-L17

**Comment by aitboudad** [comment]
The pending tasks is:

- https://github.com/ui-router/angular/pull/127
- https://github.com/ui-router/angular/blob/master/src/location/locationService.ts

**Comment by Superd22** [comment]
@aitboudad shouldn't this be a ui-router/core issue then ?
There's nothing you can do from Ng2LocationServices.

**Comment by christopherthielen** [comment]
Note the base location services class has been updated: https://github.com/ui-router/core/commit/a4629ee8b16a4a7a285c977f15eb9cd8817ea9ec#diff-aee9f1b1f04ef087e5d4b8ff17e636fc

**Comment by atmman** [comment]
@christopherthielen - Could you please tell me when this fix will be released?

**Comment by atmman** [comment]
@aitboudad @christopherthielen I tries to enable server side rendering for my project. But it looks like it's impossible to use @uirouter/angular lib with node.js. I've prepared project using angular-cli guide for server side rendering (https://github.com/angular/angular-cli/wiki/stories-universal-rendering) and tries to build backend code. Build process finishes fine but I got an error when I run backend app:
`
/home/atm/projects/proj/proj/backend/node_modules/@uirouter/angular/lib/directives/uiView.js:3
import { Component, ComponentFactoryResolver, ViewContainerRef, Input, ReflectiveInjector, ViewChild, Inject } from '@angular/core';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object./BYt (/home/atm/projects/proj/proj/backend/output/client/server/main.bundle.js:1:61842)
`

I use beta-8 version. Could you please tell me is there a way to use ui-router on the backend for now?

**Comment by atmman** [comment]
Here is my **webpack.config.js**:

```javascript
const path = require('path');
const webpack = require('webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  entry: {  server: './app.ts' },
  resolve: { extensions: ['.ts', '.js'] },
  resolveLoader: {
    modules: [
      './node_modules',
      './node_modules'
    ]
  },
  target: 'node',
  externals: [
    nodeExternals({})
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name].js',
    libraryTarget: 'commonjs'
  },
  module: {
    rules: [
      { test: /\.ts$/, loader: 'ts-loader' },
      { test: /\.json$/, loader: "raw-loader"},
    ]
  },
  plugins: [
    // Temporary Fix for issue: https://github.com/angular/angular/issues/11580
    // for "WARNING Critical dependency: the request of a dependency is an expression"
    new webpack.ContextReplacementPlugin(
      /(.+)?angular(\\|\/)core(.+)?/,
      path.join(__dirname, 'src'), // location of your src
      {} // a map of your routes
    ),
    new webpack.ContextReplacementPlugin(
      /(.+)?express(\\|\/)(.+)?/,
      path.join(__dirname, 'src')
    )
  ]
};
```

**Comment by christopherthielen** [comment]
I followed the instructions at https://github.com/angular/angular-cli/wiki/stories-universal-rendering and was able to get the UI-Router Sample App working as a universal app.

I published it [as a branch named angular-universal](https://github.com/ui-router/sample-app-angular/tree/angular-universal)

Here is the relevant commit: https://github.com/ui-router/sample-app-angular/commit/b642962601cbf4105660fd1e3abb2464ef97f4bd

To try it out, fetch the repository, switch to `angular-universal` branch, run `yarn`, then `npm run build:dynamic && npm run serve:dynamic`

**Comment by christopherthielen** [comment]
To debug the server-side app, you might want to try `node --inspect-brk dist/server.js`

**Comment by atmman9001** [comment]
@christopherthielen thanks. I've problem in my code. It was related to lib used in my backend app. I've solved it with nodeExternals in Webpack config.
I have a new question. Could you please tell me is it possible transfer current ui-router state on the backend part to the frontend app? The reason why I asking is the state changing (ui-router starts to change state from '' to '[state-name-resolved-by-url]') of a page just after of getting rendered page from the backend. Is there any units in the @uirouter/angular package?

**Comment by atmman9001** [comment]
@christopherthielen Thank you. I've solved my problem. It was related to libs in my backend app. I've excluded it from the result backend bundle with nodeModules webpack extension.

**Comment by christopherthielen** [comment]
I think this was fixed in some previous release.  Please let me know if it is not.
