### ISSUE TITLE
`No provider for NgModuleFactoryLoader!` on loadChildren

### ISSUE THREAD

**Issue by noblica** [ui-router/angular#143]
I'm currently using the 4.3 version of `@angular`, and the 1.0.0-beta.7 version of `uirouter`.
When I try to lazy load the routes, as described in the tutorials, I get the following error:
![image](https://user-images.githubusercontent.com/9339019/28371652-da94430a-6c9d-11e7-859d-c760c8349111.png)

This happens once I click on the link, and the route is supposed to load.
I'm not sure why this is happening. I've created a stand-alone repo where I reproduced this issue from scratch. Please have a look and help me with this.

Here's the repo:
https://github.com/noblica/lazyLoad

**Comment by aitboudad** [comment]
you need to define NgModuleFactoryLoader in your module see:

https://github.com/ui-router/sample-app-angular/blob/master/src/app/app.module.ts#L35

**Comment by noblica** [comment]
Thanks for the quick reply!

But this seems like something that needs to be added to the guide as well, no?

**Comment by christopherthielen** [comment]
Added to the lazyloading guide in the Angular section: https://ui-router.github.io/guide/lazyloading#angular
