### ISSUE TITLE
Provide Plugins to uiRouterFactory

### ISSUE THREAD

**Issue by moneydance** [ui-router/angular#144]
Hi is there anyway to provide custom Plugins to the uiRouterFactory so that a plugin is registered before the bootstrapping of the routes? 

Thanks,
    Ben

**Comment by christopherthielen** [comment]
Use a config fn:

```
export function configFn(router: UIRouter) { 
  router.plugin(MyPlugin);
}
```

```
  ...
    UIRouterModule.forRoot({ states: [ helloState, aboutState ], useHash: true, config: configFn })
```

Sorry about the late response.
