### ISSUE TITLE
Angular 2+ sample app link broken

### ISSUE THREAD

**Issue by iaculch** [ui-router/angular#146]
https://ui-router.github.io/resources/sampleapp/ -> https://ui-router.github.io/sample-app-ng2

![image](https://user-images.githubusercontent.com/5279217/29297372-df0b188a-81a3-11e7-89ac-a0947a1a7fea.png)

**Comment by christopherthielen** [comment]
Thanks! Fixed by 3f416fdd0f5b583ecb977b50466218556ee8cf80
