### ISSUE TITLE
ctrl / command + click open new window not working anymore.

### ISSUE THREAD

**Issue by mkoczorowski** [ui-router/angular#147]
Hi guys, I have noticed that ctrl / command + click open new window not working anymore on a link with uisref on it. Were there any changes to the behaviour? this is such an important and common thing

**Comment by christopherthielen** [comment]
Are you sure it used to work? 

Seems like a good enhancement.  Here's how we do it in AngularJS, and it should be very similar for Angular: https://github.com/angular-ui/ui-router/blob/3ab38264672cc820af539ead89e7a52370c68503/src/directives/stateDirectives.ts#L73

**Comment by mkoczorowski** [comment]
can this be achieved without modifying core ui-router code?

**Comment by christopherthielen** [comment]
Yes, this would be part of `@uirouter/angular` not `@uirouter/core`, likely right around this area: https://github.com/ui-router/angular/blob/bfa604c4acc22a5cdee5e3e8a7234c95a25ea57d/src/directives/uiSref.ts#L172-L174

**Comment by mkoczorowski** [comment]
thanks, I will look int o this when I have time

**Comment by euangoddard** [comment]
I have been looking into this issue and it should be possible to solve in the same way Angular's router does it. I've been trying to put together a PR, but when I follow the instructions to get the project up and running npm install fails inside the angular package.

```npm ERR! path /Users/euan/Sites/uirouter/angular/node_modules/@uirouter/publish-scripts/update_changelog.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/euan/Sites/uirouter/angular/node_modules/@uirouter/publish-scripts/update_changelog.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent ```

I can't find any way to work around this problem

**Comment by euangoddard** [comment]
I have submitted a PR without being able to test the code (or writing any unit tests). If you can suggest a way of solving the issue I mentioned above, I'll be happy to add the tests!

**Comment by christopherthielen** [comment]
I know how to fix that problem.  that was due to a bad release of` @uirouter/publish-scripts` so we just need to bump the dependency

**Comment by christopherthielen** [comment]
@euangoddard I bumped the package dependency.  It should install and test fine now.  I'm merging your PR as-is.  Would you mind updating and adding a couple of tests as a new PR?

**Comment by euangoddard** [comment]
@christopherthielen thanks for merging this in. I've added the tests to cover these cases in: https://github.com/ui-router/angular/pull/176
