### ISSUE TITLE
Support `exportAs` on `uiSrefActive`

### ISSUE THREAD

**Issue by kuhnroyal** [ui-router/angular#149]
To support the use-case of marking a material tab as active, the `uiSrefActive` directive needs to implement `exportAs` similar to `routerLinkActive`.

https://material.angular.io/components/tabs/overview#tabs-and-navigation

https://github.com/angular/angular/blob/4.4.0-RC.0/packages/router/src/directives/router_link_active.ts#L79

**Comment by christopherthielen** [comment]
Anyone want to take a shot at a PR?
