### ISSUE TITLE
No provider for Transition! when AOT

### ISSUE THREAD

**Issue by kolkov** [ui-router/angular#151]
Hi! When I try to build with --aot switch I see runtime error:
```
 constructor(
    private deviceService: DeviceService,
    private transition: Transition,
  ) {

  }

  ngOnInit() {
    let id = this.transition.params().id;//["id"];
    this.device = new Device();
    this.getDevice(id);
  }
```
![image](https://user-images.githubusercontent.com/3740898/30176537-772732ba-940b-11e7-80b5-4785db8cf0ca.png)

**Comment by kolkov** [comment]
```
export function getId(transition: Transition) {
  return transition.params().id
}

export const appDeviceState = {
  parent: 'app',
  name: 'device',
  url: "/device/:id",
  component: DeviceComponent,
  data: {
    requiresAuth: true
  },
  params: { id: '1' },
  resolve: [{token: 'myId', deps: [Transition], resolveFn: getId}]
};
```

```
  @Input() myId;

  constructor(
    private deviceService: DeviceService,
    //private transition: Transition,
  ) {

  }
```

![image](https://user-images.githubusercontent.com/3740898/30211189-a52c24fc-94a8-11e7-8ec6-0e5fcd5e9b99.png)

**Comment by kolkov** [comment]
As if the problem is not only in my implementation...
![image](https://user-images.githubusercontent.com/3740898/30216018-5b7a3648-94ba-11e7-91bb-60130b96fdba.png)

**Comment by kolkov** [comment]
When I turn off AOT the application is running without this error.
```
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor",
    "publish-gh-pages": "ng build --base-href=/sample-app-angular/ && shx rm -rf pages && shx mkdir pages && cd pages && git init && git remote add pages https://github.com/ui-router/sample-app-ng2.git && git fetch pages && git checkout gh-pages && git rm -rf * && shx mv ../dist/* . && git add . && git commit -m 'Update gh-pages' . && cd .. && shx rm -rf pages"
  },
```

![image](https://user-images.githubusercontent.com/3740898/30221030-79136548-94ca-11e7-8ce0-88ea67ec4d06.png)

**Comment by carlosasj** [comment]
I believe you could use this workaround until we have a proper solution:
```javascript
// Get the Transition through StateService
export function getId(stateService: StateService) {
  return stateService.transition.params().id
}

export const appDeviceState = {
  parent: 'app',
  name: 'device',
  url: "/device/:id",
  component: DeviceComponent,
  data: {
    requiresAuth: true
  },
  params: { id: '1' },
  resolve: [{token: 'myId', deps: [StateService], resolveFn: getId}]
};
```

**Comment by christopherthielen** [comment]
@kolkov  Are you using the released version of `@uirouter/angular` `1.0.0-beta.7`?  Do you have any other copies of `@uirouter/core` installed?  

Try running `npm ls` and search for `@uirouter/core`.

I found the same error message in sample-app-angular when I manually built `@uirouter/core` off `master`.  It seems to be caused by this line on this commit: https://github.com/ui-router/core/commit/10558a318ac7623574855ffb8a94f6ec74eab614

**Comment by billforward-alex** [comment]
I experienced "No provider for Transition" (on 1.0.0-beta.6 and on 1.0.0-beta.7), but it wasn't because of AoT (it happened even in dev).

in my case, I found that the problem was caused by using this import:

```ts
import { Transition } from "@uirouter/core/lib";
```

I fixed it by changing to:

```ts
import { Transition } from "@uirouter/core";
```

**Comment by christopherthielen** [comment]
@kolkov is this still an issue?  Can you tell me how to reproduce in the sample app, like your screenshot shows above?
