### ISSUE TITLE
Rename Ng2****

### ISSUE THREAD

**Issue by kolkov** [ui-router/angular#152]
Hi! Can we rename `Ng2StateDeclaration` (and other) to `StateDeclaration `? 
It seems to me that in our situation `Ng2` prefix is already something extra.

**Comment by christopherthielen** [comment]
`StateDeclaration` is already a type in `@uirouter/core` (it's what `Ng2StateDeclaration` extends).  I'd be open to `AngularStateDeclaration`.

However, I'm not happy to rename exported symbols because people are using these in their code.  This would be a breaking change.

**Comment by euangoddard** [comment]
Could you not follow many Angular 2+ library patterns and use `NgxStateDeclaration?

In terms of breaking changes, could you export an alias using the old name with a deprecation note on it to preserve backward compatibility for one major release, perhaps?
