### ISSUE TITLE
Cannot be Used in combination with normal @angular/router

### ISSUE THREAD

**Issue by pratikpanchal4472** [ui-router/angular#158]
![image](https://user-images.githubusercontent.com/8873622/30845592-b70c4d98-a2b1-11e7-8740-4f45836360e2.png)

Cannot be Used in combination with normal @angular/router. 
see attached the PIC for error.

Is there any way or config to use with @angular/router routes?
Want to use this merged with angular router routes as root and these routes as separate.

**Comment by christopherthielen** [comment]
This isn't something we plan on supporting.  What is your use case?  Why not choose either one or the other?
