### ISSUE TITLE
Lazy Loading NgModule loses url

### ISSUE THREAD

**Issue by kadamgreene** [ui-router/angular#159]
I have the following state config:

```
UIRouterModule.forRoot({
            states: [
                { name: 'app', redirectTo: 'home' },
                { name: 'home', url: '/home', component: HomeComponent },
                { name: 'counter', url: '/counter', component: CounterComponent },
                { name: 'fetch-data', url: '/fetch-data', component: FetchDataComponent },
                { name: 'secondary.**', url: '/secondary', loadChildren: './components/secondary' }
            ],
            useHash: true,
            otherwise: { state: 'home' },
            config: router => {
                router.trace.enable(Category.TRANSITION);
            }
        })
```

And the following link in my html:

```
<li uiSrefActive="link-active">
<a uiSref="secondary">
<span class='glyphicon glyphicon-th-list'></span> Secondary
</a>
</li>
```

My secondary.module.ts has the following:

```
const ROUTES = {
    states: [
        {
            name: 'secondary',
            path: '/secondary',
            component: Secondary
        }
    ]
};


@NgModule({
    imports: [UIRouterModule.forChild(ROUTES)],
    declarations: [Secondary]
})
```

and before clicking the link, it shows a url of "http://localhost/#/secondary'.   But after clicking, the url disappears from the link and it doesn't show #/secondary on the url (it stays as the last state's url).

I turned on tracing and see this:

Transition #1-0: <- Rejected "Transition#1( 'fetch-data'{} -> 'secondary.**'{} )", reason: Transition Rejection($id: 0 type: 2, message: The transition has been superseded by a different transition, detail: 'secondary'{})
trace.js:133 Transition #2-0: Started  -> "Transition#2( 'fetch-data'{} -> 'secondary'{} )"
trace.js:176 Transition #2-0: <- Success  "Transition#2( 'fetch-data'{} -> 'secondary'{} )", final state: secondary

**Comment by kadamgreene** [comment]
I tried the SampleAppNg2 that has several future / lazy loaded modules, but I couldn't get it to work:

Transition Rejection($id: 1 type: 6, message: The transition errored, detail: TypeError: Cannot read property 'get' of undefined)
$defaultErrorHandler @ stateService.js:40
(anonymous) @ stateService.js:365
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:365
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:364
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:125
(anonymous) @ zone.js:760
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:398
onInvokeTask @ core.es5.js:3881
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:397
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:165
drainMicroTaskQueue @ zone.js:593
Promise resolved (async)
scheduleQueueDrain @ zone.js:552
scheduleMicroTask @ zone.js:560
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:387
onScheduleTask @ zone.js:274
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:378
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:209
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:229
scheduleResolveOrReject @ zone.js:758
resolvePromise @ zone.js:707
(anonymous) @ zone.js:638
webpackJsonpCallback @ bootstrap 2a7361336e0e1f0032db:21
(anonymous) @ prefs.module.chunk.js:1
stateService.js:42 TypeError: Cannot read property 'get' of undefined
    at multiProviderParentChildDelta (lazyLoadNgModule.js:153)
    at applyNgModule (lazyLoadNgModule.js:113)
    at applyModule (lazyLoadNgModule.js:53)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:365)
    at Object.onInvoke (core.es5.js:3890)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:364)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run (zone.js:125)
    at zone.js:760
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:398)
    at Object.onInvokeTask (core.es5.js:3881)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:397)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:165)
    at drainMicroTaskQueue (zone.js:593)
    at <anonymous>
$defaultErrorHandler @ stateService.js:42
(anonymous) @ stateService.js:365
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:365
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:364
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:125
(anonymous) @ zone.js:760
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:398
onInvokeTask @ core.es5.js:3881
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:397
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:165
drainMicroTaskQueue @ zone.js:593
Promise resolved (async)
scheduleQueueDrain @ zone.js:552
scheduleMicroTask @ zone.js:560
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:387
onScheduleTask @ zone.js:274
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:378
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:209
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:229
scheduleResolveOrReject @ zone.js:758
resolvePromise @ zone.js:707
(anonymous) @ zone.js:638
webpackJsonpCallback @ bootstrap 2a7361336e0e1f0032db:21
(anonymous) @ prefs.module.chunk.js:1

**Comment by kadamgreene** [comment]
Nevermind, I'm a complete idiot :-)

I altered my code to contain the StatesModule, and discovered I had put path not url...

const ROUTES : StatesModule = {
    states: [
        {
            name: 'secondary',
            **url: '/secondary',**
            component: Secondary
        }
    ],
    
};

**Comment by christopherthielen** [comment]
Nice, glad you figured it out
