### ISSUE TITLE
Cannot find module '@uirouter/angular'.

### ISSUE THREAD

**Issue by cullsin** [ui-router/angular#161]
Hi, 

I am a newbie, angular 4.x. I have installed as suggested below.
npm install --save ui-router-ng2
I am getting a below Error. Can you please suggest me. 
Cannot find module '@uirouter/angular'.

Raja K

**Comment by mkoczorowski** [comment]
you should not be using ui-router-ng2 please remove this dependency.

Instead
npm install @uirouter/angular -S

**Comment by christopherthielen** [comment]
`npm install --save @uirouter/angular`

@cullsin did you find outdated documentation somewhere that recommends installing `ui-router-ng2`?  If so, can you point it out?

**Comment by christopherthielen** [comment]
Ah, I found them.  I've updated the about page:  https://github.com/ui-router/ui-router.github.io/commit/3fd4a387ad5babb119f6bc700a3deea9d07a48ca
