### ISSUE TITLE
[uiSref] sets the href to only a partial url for lazy loaded routes

### ISSUE THREAD

**Issue by bouncehead13** [ui-router/angular#164]
There is a bug in the way `uiSref` builds the `href` attribute for lazy loaded modules.

**The scenario**

The shop module & its routes are all lazy loaded.
```
{
    name: 'shop.**',
    url: '/shop',
    loadChildren: './shop/module#ShopModule'
}
```

Lazy Loaded Route (one of a few I have defined)
```
{
    name: 'shop.item',
    url: '/product/:slug',
    resolve: [
        {
            token: 'product',
            deps: [ Transition, Store ],
            resolveFn: GetProductDetailResolve
        }
    ]
}
```

From my home page, I have a link that sends you to a specific product.
```
<a uiSref="shop.item" [uiParams]="{ slug: product.slug }"></a>
```

**Problem**
The problem is the `href` gets set as `href="/shop"` instead of `href="/shop/product/product-slug"`. I know this is because the lazy loaded routes have not been loaded yet so it doesn't know what to resolve. However, this is a major bug because SEO bots cannot crawl the homepage because all links point to just `/shop`. In addition, right-click and open link in a new tab opens to `/shop`. Both cases should link to the fully built url (`href="/shop/product/product-slug"`).

**Question**
Is there a future release to address this or any suggested alternatives to make this work? Thanks!

**Comment by christopherthielen** [comment]
This is a design tradeoff with lazy loaded states in ui-router.  Angular Router, for example, take another approach and does not have this problem because 1) there are no named routes and 2)  links are constructed "manually" (as opposed to reading state definitions).

I'm open to your ideas on how to address this.  Two thoughts that come to mind:

1) construct URL manually: `<a uiSref="shop.item" [uiParams]="{ slug: product.slug }" href="/shop/product/:slug"></a>`

Easy to use, lots of boilerplate, potentially error-prone

2) put nested state's urls in the future state definition:
```
{
    name: 'shop.**',
    url: '/shop',
    childUrls: { '.item': '/product/:slug' }
    loadChildren: './shop/module#ShopModule'
}
```

Less boilerplate, but urls are still duplicated in two places

3) your idea

**Comment by mkoczorowski** [comment]
we can define all states at the the start.. but lazy load module when accessing them ? Thats how I had it working in A1

**Comment by bouncehead13** [comment]
@christopherthielen 

**1)** I didn't actually this, but would manually defining the href actually work? I think the `uiSref` directive would override that href with the incorrect `/shop` route.

**2)** This one would technically work, but that really creates a lot of duplicate routes defined in our main route file.

@mkoczorowski I'm curious to hear more detail, possible a small code snippet, on what you're alluding to. Your idea sounds like the suggested option 2 from @christopherthielen.

I'm glad you see the motivation to finding a solution for this problem. I'll have to brain storm some more.

**Comment by christopherthielen** [comment]
I tried some things and I think there's a reasonable solution when all states are known ahead of time: https://stackblitz.com/edit/ui-router-angular-jc2k6z?file=home%2Fhome.module.ts

All the states are registered as normal states, but with url and name only.  The root of the lazy load tree has a `loadChildren` added.  When the child module is lazy loaded, it copies the URLs from the original states to the full states (which have the `component` and `resolve`, etc properties).  

With this approach, the URLs aren't duplicated in the pre-lazy-load and post-lazy-load state defs.  They're in the pre-lazy-load definitions only.  This avoids future states altogether and assumes the developer will update the states manually during lazy loading.

This requires the latest `@uirouter/angular` v`1.0.0-rc.0` which relaxes the requirements of `loadChildren`.

```js
export const states: Ng2StateDeclaration[] = [
  { name: 'home', component: HomeComponent },
  { name: 'home.nest', component: NestComponent },
];

export function config(uiRouter: UIRouter, injector: Injector, module: StatesModule) {
  const registry = uiRouter.stateRegistry;
  // copy url from original state defs
  states.forEach(state => state.url = registry.get(state.name).url);
  // Deregister original states
  registry.deregister('home');
  // Add states to module declaration
  module.states = states;
}

@NgModule({
  imports:      [ UIRouterModule.forChild({ config }) ],
  declarations: [ HomeComponent, NestComponent ],
  entryComponents: [ HomeComponent, NestComponent ],
})
export class HomeModule { }
```

**Comment by christopherthielen** [comment]
Closing because I think this is a reasonable approach/workaround.  Let me know if you disagree.

**Comment by mkoczorowski** [comment]
I have actually spend a few days trying to implement the above solution. Problem is that registry.deregister('') re-runs config function again. Having deregister in a loop results in lots and lots of calls to config function. For example I called deregister twice in config function resulting in function being executed 42 times! Is there just an option to override a state ? without deregisteing and registering again ?

**Comment by floreks** [comment]
@christopherthielenn I'm not sure if this workaround helps me. We have a bit different setup and I can't really make it work this way.

We have an abstract state `x` that is lazy loaded:
```js
export const stateName = 'pod';
export const stateUrl = '/pod';

export const podFutureState: Ng2StateDeclaration = {
  name: `${stateName}.**`,
  url: stateUrl,
  loadChildren: './resource/workloads/pod/module#PodModule',
};

export const podState: Ng2StateDeclaration = {
  abstract: true,
  parent: chromeState.name,
  name: stateName,
  component: ProxyComponent,
};
```
It has 2 child states:
```js
export const podListState: Ng2StateDeclaration = {
  name: `${stateName}.list`,
  url: stateUrl,
  component: PodList,
};

export const podDetailState: Ng2StateDeclaration = {
  name: `${stateName}.detail`,
  url: addNamespacedResourceStateParamsToUrl(stateUrl),
  component: PodDetailComponent,
};
```

Module declaration is as follows:
```js
@NgModule({
  imports: [
    SharedModule,
    ComponentsModule,
    ResourceModule,
    UIRouterModule.forChild({states: [podState, podListState, podDetailState]}),
  ],
  declarations: [PodList, PodDetailComponent],
})
export class PodModule {}
```

They are then registered in our `RootModule`:
```js
UIRouterModule.forRoot({
      states: [
        // Core states
        chromeState,
        loginState,
        // Lazy-loaded states
        // Workloads section
        podFutureState,
       ...
        // Config section
        secretFutureState,
      ],
```

Now let's say that in component that is a part of `PodModule` I'd like to create a link to details state of secret state. Right now it just returns link to future state.

```js
return this.state_.href(secretDetailState.name, params);
```

Any idea how to solve this?

**Comment by paulodrade** [comment]
@christopherthielen I this is a very good implementation anyways. 

If you could just make `ui-router` works with `pushState/onpopstate` would be fantastic!!! Do you think it would be possible?

**Comment by paulodrade** [comment]
Any update?

**Comment by lacroixdavid1** [comment]
I have automated @christopherthielen for my use case using webpack. 

During the build process, I look for lazy module states and add them to the app.module states via a loader.

**Comment by Plonq** [comment]
> I have automated @christopherthielen for my use case using webpack.
> 
> During the build process, I look for lazy module states and add them to the app.module states via a loader.

@lacroixdavid1 would you mind sharing your solution? I assume you wrote a custom loader to do this?
