### ISSUE TITLE
Better support for animation of routed components

### ISSUE THREAD

**Issue by christopherthielen** [ui-router/angular#165]

**Comment by Hypercubed** [comment]
Any details on how it is done currently?  I can animate `:enter` but not `:leave` in a hybrid app using ui-router.

**Comment by christopherthielen** [comment]
That's interesting.  I was able to animate `:leave` but not `:enter` with the current release of `@uirouter/angular`

Here's a stackblitz showing the necessary modifications to the `UIView` component and how it will work eventually

**Comment by Hypercubed** [comment]
I'm doing something similar.  Using animation queries and 

```
<div class="content" [@routerTransition]="state">
   <div ui-view></div>
</div>
```

I am using an older version of `uirouter` and a hybrid app....

**Comment by mkoczorowski** [comment]
@Hypercubed can you give an example how you are achieving this ?

**Comment by Hypercubed** [comment]
@mkoczorowski In the end I move the animation into each component.  Each component has an `:enter` animation and forces a state change on transition `onStart` and delays the actual route change.

I believe if I was using a newer ui-router this would not be an issue.

**Comment by christopherthielen** [comment]
https://stackblitz.com/edit/ui-router-fade-transitions?file=app/app.component.ts
