### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by kptLucek** [ui-router/angular#170]
**Error**
`
ERROR in Error: Metadata version mismatch for module /someDir/node_modules/@uirouter/angular/lib/index.d.ts, found version 4, expected 3
`

**Environment**
`@angular/cli`: 1.4.5
`node`: 6.11.2
`os`: linux x64
`@angular/animations`: 4.4.6
`@angular/common`: 4.4.6
`@angular/compiler`: 4.4.6
`@angular/core`: 4.4.6
`@angular/forms`: 4.4.6
`@angular/http`: 4.4.6
`@angular/platform-browser`: 4.4.6
`@angular/platform-browser-dynamic`: 4.4.6
`@angular/router`: 4.4.6
`@angular/cli`: 1.4.5
`@angular/compiler-cli`: 4.4.6
`@angular/language-service`: 4.4.6
`@uirouter/angular`: "1.0.0-rc.0"
`typescript`: 2.3.4

I'm facing this issue once i've updated package from `1.0.0-beta.9` to `1.0.0-rc.0` 

Any ideas?

**Comment by hijha** [comment]
I'm having the same issue.

**Comment by CristianDuta** [comment]
I'm also facing the same issue, can this issue be labeled as 'help wanted'??

**Comment by lgaitan** [comment]
I'm also having the same issue, downgrading to 1.0.0-beta.9 fix it.
It seems that the package was compiled for angular v5

**Comment by bouncehead13** [comment]
Same problem for me as well. I'm not quite ready to upgrade to Angular 5 and it appears the `1.0.0-rc.0` was definitely built using Angular 5.x.

@christopherthielen Do you think a fix for this can be made? I wanted to try out the new lazyLoad features you tagged with that release.

**Comment by christopherthielen** [comment]
`1.0.0-rc.1` just released.  It should be built with angular 4.4.6.  I have no idea how I managed to build the previous release using v5!

lmk if this fixes the problem for ya'll
