### ISSUE TITLE
Why this repo exist if Angular 2+ provides built-in routing module

### ISSUE THREAD

**Issue by amineparis** [ui-router/angular#172]
this will disperse contribution efforts !!

**Comment by mkoczorowski** [comment]
because its way better! Obsolete issue

**Comment by amineparis** [comment]
why don't you contribute to angular to make it better rather than dispersing work force upon multiple parallel tools that serve the same need ?

**Comment by mkoczorowski** [comment]
because uirouter is different concept. It navigates trough states not urls as angular router does. Please try it for yourself.

**Comment by amineparis** [comment]
The thing I hate the most about programming is dispersion of tools, Os's, languages, libraries, frameworks. don't you think you would better debate with Angular designers this way one will convince another. In addition you have only 154 stars, that means community finds this tool useless for Angular 2+

**Comment by mkoczorowski** [comment]
I dont really understand what are you trying to achieve here. No one is forcing you to use this tool. You are free to use whatever you like.  there are lots of angular open source packages but no one is forcing you to use them. Whats your problem? As for the stars, I suggest you do a bit more research on uirouter for angularjs which was precursor to this project and stop moaning. No one is forcing you to use it. If you not interested then just go away. No point in arguing.

**Comment by amineparis** [comment]
Thnak you, you are so kind
