### ISSUE TITLE
RFC: OnLazyLoadHook

### ISSUE THREAD

**Issue by carlosasj** [ui-router/angular#173]
I was facing a problem with Lazy Loading modules and the UI-Router: Some modules are too big and take some (noticeable) time to load, meanwhile the user did not received any feedback, so he keeps clicking the link until the page changes.
I searched the docs for a solution to show some message while the module is downloading, but I had no success.

**Did I miss something?**

-------------------------

My (not so good) solution to this was adding a `MutationObserver` on the `constructor` of `app.component.ts`, to listen to `head` changes and show a "Loading..." message to the user:

```js
...
const showLoadingMessage = () => { /* My Logic */ };
const hideLoadingMessage = () => { /* My Logic */ };
...
const observer = new MutationObserver(function (m) {
    const node = m[0].addedNodes[0];
    if (node.nodeName === 'SCRIPT' &&
        (<string>node['src']) &&
        (<string>node['src']).endsWith('.module.chunk.js')
    ) {
        showLoadingMessage();
        node.addEventListener('load', hideLoadingMessage);
    }
});
observer.observe(document.head, { childList: true });
```

If there is no solution yet to this problem, I would like to suggest a enhancement, because I think this  can be useful to more projects. And even if this enhancement is denied, at least it will be documented as a workaround to this problem.

**Comment by christopherthielen** [comment]
You should be able to implement this with these existing primitives: 

- `lazyLoad` property on a state
- A Transition Hook when entering a lazyload state
- A Transition promise

```js
.onStart({ entering: (state) => state.lazyLoad }, transition => {
  showLoadingMessage();
  transition.promise.then(hideLoadingMessage, hideLoadingMessage);
});
```

**Comment by christopherthielen** [comment]
Note: priority: 1 is necessary because [the lazy load hook itself is a priority 0 onBefore hook](https://github.com/ui-router/core/blob/24da33201e55361e6e040b73306dd878e6f06b31/src/hooks/lazyLoad.ts#L69-L70).
