### ISSUE TITLE
Angular Component Lifecycle ngOnChanges not being called when view loaded with resolves

### ISSUE THREAD

**Issue by mtraynham** [ui-router/angular#174]
I have a component for a route that takes a few `@Input` resolvables.  Those are all resolved by Promises on the route itself.  When I go to the route, it seems to load the data correctly and apply the input bindings, but it seems `ngOnChanges` is not called.  The `UIView` directive seems to trigger a [change detection check](https://github.com/ui-router/angular/blob/master/src/directives/uiView.ts#L202) upon the newly created component, but I'm still not seeing that `ngOnChanges` function get called.

That `this._componentRef.changeDetectorRef.markForCheck()` call triggers an Angular function on the ViewRef:
```ts
    /**
     * @return {?}
     */
    ViewRef_.prototype.markForCheck = /**
     * @return {?}
     */
    function () { markParentViewsForCheck(this._view); };
```

to check all parent views:
```ts
function markParentViewsForCheck(view) {
    var /** @type {?} */ currView = view;
    while (currView) {
        if (currView.def.flags & 2 /* OnPush */) {
            currView.state |= 8 /* ChecksEnabled */;
        }
        currView = currView.viewContainerParent || currView.parent;
    }
}
```

None of those fall into that if statement `currView.def.flags & 2 /* OnPush */`, and so it seems like that function does nothing.

It seems like [viewRef.detectChanges()](https://github.com/ui-router/angular/commit/3d532b65529991a9b1f1dfc2ac043698eba5c301#diff-54266fe22d596e284de14a319d6571f5L290) was previously used, but I've attempted to use that locally without success.

**Comment by christopherthielen** [comment]
Yes, we switched from `detectChanges` to `markForCheck`.  Using `detectChanges` caused some [problems with animation code](https://gitter.im/angular-ui/ui-router?at=59f64b14614889d47516f531), presumably because it was happening within an existing change detection cycle.  By switching to `markForCheck` angular gets to schedule change detection (for the `UIView`) when it decides it is necessary.

I'm not sure why `ngOnChanges` is not being called.  I don't think it's due to the change in the UIView.  This issue will require more research.

**Comment by christopherthielen** [comment]
Here's a [forked stackblitz example](https://stackblitz.com/edit/ui-router-angular-r7brc8?file=UIView2.component.ts) with a clone of the `UIView` directive (`UIView2.component.ts`) to play with.

**Comment by christopherthielen** [comment]
https://github.com/angular/angular/issues/13245#issuecomment-264958693

Looks like this is intentional (we modify component properties; we do not create any template bindings)

**Comment by mtraynham** [comment]
@christopherthielen thank you for looking into this!  I guess if it's *working as intended*, we can probably close this.  It is somewhat strange that it differs from the normal component lifecycle, but I guess once the view is loaded those inputs would never actually change (correct me if I'm wrong).

As a temporary workaround, I was using using `ngOnInit` instead and not checking if the properties changed, rather assuming they had been resolved correctly.  Looks like I'm sticking with that.

Feel free to close this.

**Comment by christopherthielen** [comment]
I would like this to work also.  I hope angular itself will support this in the future. Closing for now.
