### ISSUE TITLE
StateService is broken

### ISSUE THREAD

**Issue by FlamesoFF** [ui-router/angular#188]
Code:
```
...
import {StateService} from '@uirouter/angular';

@Component({
    selector: 'app-tabs',
    templateUrl: './tabs.component.html',
    styleUrls: ['./tabs.component.scss'],
    providers: [
        StateService
    ]
})

export class Component implements OnInit {
    constructor(
        private state: StateService
    ) {
...
```
Result:

> Uncaught Error: Can't resolve all parameters for Component : ([object Object], ?).

**Comment by christopherthielen** [comment]
I've seen injection errors for `@uirouter/core` services fail when more than one copy of `@uirouter/core` is bundled.

Can you show your `package.json` dependencies and devDependencies?  

Run `npm ls` and look for multiple copies of `@uirouter/core`.

**Comment by christopherthielen** [comment]
for example, multiple copies are shown here (from output of `npm ls`):

```
npm ls | grep uirouter.core
│ │ └── @uirouter/core@5.0.13
│ │ │ └── @uirouter/core@5.0.13
│ │ ├── @uirouter/core@5.0.5
│ │   ├── @uirouter/core@5.0.13 deduped
│ │ └── @uirouter/core@5.0.1
│ │ └── @uirouter/core@5.0.11 deduped
│ ├── @uirouter/core@5.0.11
│   ├── @uirouter/core@5.0.11 deduped
```

**Comment by FlamesoFF** [comment]
@christopherthielen I have exactly one dependency `"@uirouter/angular": "^1.0.0-rc.2"` in my package.json with no duplicates. Also my IDE always give warnings about dependency duplications.
And `npm ls` shows only this:
`
+-- @uirouter/angular@1.0.0-rc.2
| +-- @uirouter/core@5.0.13
| +-- @uirouter/rx@0.4.5
`

**Comment by FlamesoFF** [comment]
@christopherthielen It's ok now. I fixed it by simple deleting "node_modules" folder and reinstalling of the dependencies.
