### ISSUE TITLE
support shorthand for named views' components

### ISSUE THREAD

**Issue by christopherthielen** [ui-router/angular#19]
https://github.com/angular-ui/ui-router/pull/3063
This issue moved from https://github.com/angular-ui/ui-router/issues/3065

Named views in ng2 currently look like this:

``` js
views: {
  foo: { component: FooCompoent }
}
```

We should also support the same shorthand as we do in ng1:

``` js
views: {
  foo: FooCompoent
}
```

**Comment by johnnliu** [comment]
thank you for this issue.  as someone trying uiRouter with Angular-Cli for the first time it was indeed confusing that `views: { foo: fooComponent }` didn't seem to do anything and `views: { foo: { component: fooComponent } }` was the correct way.

**Comment by mkoczorowski** [comment]
yeah, I dont think this: `views: { foo: { component: fooComponent } }` is documented anywhere.
this mix of ng1 and n2 ducmentation is really confusing

**Comment by surfjedi** [comment]
Yes this is not documented any where
