### ISSUE TITLE
how do I navigate inside the component

### ISSUE THREAD

**Issue by cullsin** [ui-router/angular#199]
Hi, 

Can you please suggest me how do I navigate to different state from my component. 
I am using angular 5 + angular ui router. 

Thanks,
Raja K

**Comment by mkoczorowski** [comment]
stateService.go ..
https://ui-router.github.io/ng2/docs/latest/classes/state.stateservice.html#go

**Comment by cullsin** [comment]
Hi, 

Sorry, It's pointing to angular 1.x. Suggest me for angular 5. which module I shall Import ?

Raja K

**Comment by christopherthielen** [comment]
```
import { StateService } from '@uirouter/core';

@Component({
  template: `<a (click)="handleClick()">Click me</a>`
})
export class MyComponent {
  constructor(public $state: StateService) {}
  handleClick() {
    this.$state.go('somestate');
  }
}
```
