### ISSUE TITLE
Write simple angular-cli guide

### ISSUE THREAD

**Issue by christopherthielen** [ui-router/angular#2]
include lazy loading

**Comment by niwrA** [comment]
I am using this for angular-cli and the basics seem to work fine as long as I was already ng serving the app, but when I start it with the UIRouterModule in my main app, the build just stops at some point. I'll create an issue. When I get that solved, perhaps I can help with this.

**Comment by mkoczorowski** [comment]
@niwrA did you manage to get lazy loading working with abgular-cli 1.0 webpack ?

**Comment by christopherthielen** [comment]
@mkoczorowski the sample app shows lazy loading working with angular-cli 1.0+

https://github.com/ui-router/sample-app-ng2

**Comment by mkoczorowski** [comment]
@christopherthielen thank you. I spend days trying to figure it out!
I was missing this bit 

 providers   : [
    { provide: NgModuleFactoryLoader, useClass: SystemJsNgModuleLoader }
  ],

everything started woking finally :D
