### ISSUE TITLE
[Resolve] async ResolvePolicy "RXWAIT" does not behave as expected

### ISSUE THREAD

**Issue by christopherthielen** [ui-router/angular#20]
This issue moved from: https://github.com/angular-ui/ui-router/issues/3066

When returning an errored observable from a resolve factory the state transition never happens (state home.observable-that-throws). Furthermore, the items that are emitted after the first item don't seem to be passed on to the stream that is resolved (home.observable).

Plunker: http://plnkr.co/edit/x2mTrhH3RQuNV4fcXSrO?p=preview
Expected: http://plnkr.co/edit/MXMAAWLDD6jGUz99SDlG?p=preview

**Comment by jspizziri** [comment]
☹️

**Comment by killersite** [comment]
So just to be clear - using Observables in resolves are not working yet? 

Can you describe the best way to use observables now? 
will using the operator toPromise() work when I want to wait for a single value?

**Comment by Klaster1** [comment]
@killersite if you need a single value, then toPromise will be perfectly fine. When you need multiple values, you can arrange two (or more) resolves: one eagerly passes an Observable to component binding (you'll have to subscribe inside component) and another resolve that waits for first value of the first Observable via toPromise.

**Comment by atdiff** [comment]
Curious if there is any update on this issue

**Comment by wawyed** [comment]
fixed in https://github.com/ui-router/angular/blob/master/CHANGELOG.md#500-2019-10-02
