### ISSUE TITLE
Injector in UIRouterModule.forRoot's config is creating separate instances

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [ui-router/angular#202]
App's main module:

```
function RouterConfig(uiRouter: UIRouter, injector: Injector, module: StatesModule): any {
 const eventManager: EventManager = injector.get(EventManager);
}
```
```
imports: [
    (...)
    UIRouterModule.forRoot({ config: RouterConfig }),
    (...)
  ],
providers: [
    (...)
    EventManager
]
```

later on, in the application first main component:

```
@Component({
  selector: 'app-root',
  template: '<ui-view></ui-view>'
})
export class AppComponent {
  constructor(private eventManager: EventManager) {
}
```

These are two different instances of EventManager. Is this expected behaviour? 

If not, how can I make sure that the configuration function for router accesses the same injectables that will then be used in the whole application (in components)?

If so, how can I actually provide configuration (that reaches for other injectable components) for UI-Router, once the application starts? If I'm reaching for TransitionService in AppComponent, it's already too late, as it shows up during the first transition and certain hooks aren't triggering (for instance, onBefore).

**Comment by christopherthielen** [comment]
> These are two different instances of EventManager. Is this expected behaviour?

No, definitely not.   Here's a stackblitz that shows the expected behavior: https://stackblitz.com/edit/github-4lmy4j?file=src/app/home.component.ts

Can you please fork the stackblitz and reproduce the described problem?

**Comment by sebastian-zarzycki-es** [comment]
Weird. I'm unable to reproduce it now, either on stackblitz or in my own code. Something must have changed in last two weeks (I did npm install / update multiple times), either for angular, angular-cli or ui-router itself.

**Comment by christopherthielen** [comment]
sounds good.  Closing for now then.
