### ISSUE TITLE
UI-Router doesn't wait for App_Initializer

### ISSUE THREAD

**Issue by shyamal890** [ui-router/angular#206]
UI-Router triggers route change as defined in `config section` before `App_Initializer` function is executed. In the below example home state's `resolveFn` is triggered before `App_Initialzer's` resolves

**app.module.ts**

```
@NgModule({
  declarations: [
    AppComponent,
    routingComponents
  ],
  imports: [
    BrowserModule,
    UIRouterModule.forRoot(
      { states: appRoutes, 
        useHash: true ,
        config: uiRouterConfigFn
      }
    ),
  ],
  providers: [
    {
        provide: APP_INITIALIZER,
        useFactory: test,
        multi: true
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

function test(): Function {
  return () => delay();
}

function delay(){
  var deferred = new Deferred<any>();
  console.log("Initialization started: " + new Date());
  setTimeout(() => {
    console.log("Initialization Done: " + new Date());
    deferred.resolve();
  }, 5000); // Wait 3s then resolve.
  return deferred.promise;
}
```

**app.routes.ts**

```
export const routingComponents = [
    HomeComponent
  ];


let home = {
    name: 'home',
    url: '/home',
    component: HomeComponent,
    resolve:[
      {
        token: 'te',
        resolveFn:($state: StateService) =>{
          var deferred = new Deferred<any>();
          console.log("testing Home Component");
          deferred.resolve();
          return deferred.promise;
        }
      }
    ]
  }
  
  export const appRoutes = [
    home
  ];
  
  export function uiRouterConfigFn(router: UIRouter, injector: Injector) { 
    // If no URL matches, go to the `hello` state by default
    router.urlService.rules.otherwise({ state: 'home' });
  }
```

Have attached the full project for reference.

[test.zip](https://github.com/ui-router/angular/files/1685805/test.zip)

**Comment by shyamal890** [comment]
@christopherthielen can you please share your thoughts on this, am at my wits end trying to solve this issue.

**Comment by christopherthielen** [comment]
As a workaround you can use `deferIntercept` In the router configuration function and manually call `listen` and `sync` after your initializer is fone

**Comment by christopherthielen** [comment]
You could also move your initializer logic into an `onBefore` transition hook that runs on the first transition

**Comment by shyamal890** [comment]
That would mean AppComponent gets intialized, loading screen goes away! Why not have a way to initialize ui-router after app_intializer?
Is there a way to manually initializing ui-router? We can init after app initialization 
 
  On Sun, Feb 4, 2018 at 1:18 AM, Chris Thielen<notifications@github.com> wrote:   
You could also move your initializer logic into an onBefore transition hook that runs on the first transition

**Comment by shyamal890** [comment]
`deferIntercept` solves the issue.

**Comment by christopherthielen** [comment]
FWIW, ui-router itself uses an `APP_INITIALIZER` to perform the initial `sync()`: https://github.com/ui-router/angular/blob/c1c275f77c37f9b1fec7ddcf05d8bd7fe3d444c6/src/providers.ts#L175

**Comment by jensbodal** [comment]
Can also load the config in `main.ts` and provide the config.

```
fetch('/app-config-url').then(data => data.json().then((appConfig) => {
  platformBrowserDynamic(
    [{ provide: 'AppConfig', useValue: appConfig }]
  )
  .bootstrapModule(AppModule)
```

This is just a simple example using fetch and without typesafety.
