### ISSUE TITLE
[Transition] prevent memory leak

### ISSUE THREAD

**Issue by aitboudad** [ui-router/angular#21]
I noticed the memory is growing after each new transition
I did some debugging and I noticed that all created transition not destroyed due to the usage of it's reference in:

- [UISrefStatus](https://github.com/ui-router/ng2/blob/master/src/ng2/directives/uiSrefStatus.ts#L198)
- Circular references in [applyRootResolvables](https://github.com/ui-router/core/blob/master/src/transition/transition.ts#L172)
- https://github.com/ui-router/core/blob/master/src/globals.ts#L82

![selection_049](https://cloud.githubusercontent.com/assets/1753742/21893797/89dfd6a2-d8d4-11e6-8d9f-7df9c601ce3f.png)
![selection_050](https://cloud.githubusercontent.com/assets/1753742/21893890/ee2f4bd8-d8d4-11e6-87e7-22d6c06544d0.png)

**Comment by christopherthielen** [comment]
I appreciate the legwork you're putting in.  I'll dig into this before releasing "final"
