### ISSUE TITLE
Use of APP_INITIALIZER breaks in AOT builds

### ISSUE THREAD

**Issue by kboucher** [ui-router/angular#210]
While successfully using Angular's APP_INITIALIZER to load configuration and i18n files before routing, I am confronted with a build warning when attempting AOT compilation and subsequent runtime errors in my application. _(Using `@uirouter/angular@1.0.0`)_

AOT compilation warning:
```
    WARNING in ./aot/src/app/app.module.ngfactory.ts
    export 'appInitializer' (imported as 'i14') was not found in '@uirouter/angular/lib/providers
```
Runtime error:
```
    main.js:5 Uncaught TypeError: y.appInitializer is not a function
```

Relevant line from app.module.ngfactory.ts:
```
     import * as i14 from '@uirouter/angular/lib/providers';
```

`appInitializer` function in @uirouter/angular/lib/providers.js:
```
    export function appInitializer(router) {
        return function () {
            if (!router.urlRouter.interceptDeferred) {
                router.urlService.listen();
                router.urlService.sync();
            }
        };
    }
```

`appInitializer` function in @uirouter/angular/lib/providers.d.ts:
```
    export declare function appInitializer(router: UIRouter): () => void;
```

`providers` declaration from NgModule (AppModule):
```
    providers: [
        AppConfig, {
            provide: APP_INITIALIZER,
            useFactory: initResources,
            deps: [AppConfig, TranslationConfigModule, UIRouter],
            multi: true,
        },
        AppService,
        ArticleService,
        CategoryService,
    ]
```

`initResources` function:
```
    export function initResources(config: AppConfig, translate: TranslationConfigModule, uiRouter: UIRouter) {
        const router = uiRouter;

        return function() {
            config.load(translate).then(function() {
                router.urlRouter.listen();
                router.urlRouter.sync();
        });
    }
```

As indicated, this setup works fine in development builds. It seems to be an AOT compatibility issue, but even after tinkering around with the syntax in the providers .d.ts and .js files, I could not achieve a successful build.

**Comment by christopherthielen** [comment]
Can you give more details about your build setup?  This works fine using angular-cli.  Here's an example branch (`issue-210`) based on the sample app: https://github.com/ui-router/sample-app-angular/tree/issue-210

**Comment by christopherthielen** [comment]
The `@uirouter/angular/lib/providers` line is suspicious.  I don't think anything should be imported from `@uirouter/angular/lib/*

**Comment by kboucher** [comment]
@christopherthielen Thank you for updating the sample app to demonstrate `APP_INITIALIZER` integration.

We are currently using a custom build process to account for some peculiarities in our deployment of Angular apps. (Specifically, we are using the Jetray yeoman generator to bootstrap Angular apps for deployment as Liferay portlets: https://github.com/xtivia/generator-jetray/tree/master/generators/Angular/templates/src/main/ui.)

I hope to find some time this week to dig into this issue again, given your example and your comments above. I will comment later with my findings.

Thanks again!

**Comment by kboucher** [comment]
It seems that this issue was related to the custom build process mentioned above. Specifically, once I updated the Angular runtime that is being served with these apps, the issue was resolved. The glaring distinction in the two versions of the runtime were an inclusion of `appInitializer` as an export.

Curiously, the only difference between the runtime I had been using and the new one, is an upgrade from UIRouter `1.0.0-beta.6` to `1.0.0-rc.2.` Would you be able to confirm that support for `appInitializer` was absent from `1.0.0-beta.6`?

_And yes, I will be submitting a PR to upgrade that runtime to use `@uirouter/angular@1.0.0`._

Your example was instrumental in the process of debugging this issue, so, thanks again!
