### ISSUE TITLE
TypeError: observable$.cache is not a function

### ISSUE THREAD

**Issue by tsheils** [ui-router/angular#211]
It appears as though resolvable.js is calling the observable$.cache function, even though it was was removed in rxjs 5.0.0-r.c.1 https://github.com/ReactiveX/rxjs/blob/5.0.0-rc.1/CHANGELOG.md
@uirouter/rx depends on "rxjs": "^5.0.3",
This prevents Observables from being used in a resolve function 
plunkr: https://plnkr.co/edit/Jt3XCJ316lBD1WKCSFxq?p=preview

![image](https://user-images.githubusercontent.com/6415791/36039625-05e4796e-0d91-11e8-8bf2-8ca7aeb1d6dd.png)

**Comment by hordesalik** [comment]
You can use Observable.prototype.toPromise()

**Comment by wawyed** [comment]
Fixed in https://github.com/ui-router/angular/blob/master/CHANGELOG.md#500-2019-10-02
