### ISSUE TITLE
Need way to make uiSref optional

### ISSUE THREAD

**Issue by CanyonJ** [ui-router/angular#244]
We have a generic component that contains `<a uiSref={{targetState}}>`. How do I make uiSref optional so that if targetState isn't supplied, clicking on the list row won't cause an error?  tried something like `[attr.uiSref]=targetState`, didn't work when targetState was defined as a valid state string.

It would be nice if null, undefined, or empty string did nothing on a click instead of calling state.go.

**Comment by christopherthielen** [comment]
agreed, thanks for reporting
