### ISSUE TITLE
Lazy Loading, preloadingStrategy and AoT

### ISSUE THREAD

**Issue by qkevinto** [ui-router/angular#252]
I cannot seem to find any mention of an equivalence to [`preloadingStrategy`](https://angular.io/api/router/PreloadAllModules) when using `ui-router` to lazy load modules with AoT.

It's quite easy to do when implementing with JiT as `loadChildren` is just a loader function and can be "preloaded" like so:
```
{
    name: 'foo.**',
    url: '/foo',
    loadChildren: () => import('./components/foo')
        .then(module => module.FooModule)
}

...

const deregisterPreloadLazyLoadedRouteHook = router.transitionService.onSuccess({}, transition => {
    transition.router.stateRegistry.get().filter((state: Ng2StateDeclaration) => !!state.loadChildren).forEach((state: Ng2StateDeclaration) => {
        if (typeof state.loadChildren === 'function')
            state.loadChildren();
    });
    deregisterPreloadLazyLoadedRouteHook();
});
```

But when lazy loading with AoT, `loadChildren` is just a string:
```
{
    name: 'foo.**',
    url: '/foo',
    loadChildren: './components/foo#FooModule'
}
```

Is there support for getting `ui-router` to pre-load these modules?

**Comment by christopherthielen** [comment]
I think you're looking for [`StateService.lazyLoad`](https://ui-router.github.io/ng2/docs/latest/classes/state.stateservice.html#lazyload).

Instead of calling `state.loadChildren();` you should be able to call `transition.router.stateService.lazyLoad(state)`

**Comment by qkevinto** [comment]
Cheers @christopherthielen, thanks for the tip – I'll test it out when revisit this issue.

Though to somewhat answer my own question, here's how I've approach a the solution by using `SystemJsNgModuleLoader` (which you've probably already done if you've followed the [ui-router lazy loading guide](https://ui-router.github.io/guide/lazyloading)):

Provide `SystemJsNgModuleLoader` as `NgModuleFactoryLoader` in `app.module.ts`:
```
...
{ provide: NgModuleFactoryLoader, useClass: SystemJsNgModuleLoader },
...
```

`ui-router.config.ts` or where ever you keep your transition hooks:
```
// Preload all lazy loaded routes after first load to make navigation faster without hindering initial load
const deregisterPreloadLazyLoadedRouteHook = router.transitionService.onSuccess({}, transition => {
    const loader = injector.get(NgModuleFactoryLoader);
    transition.router.stateRegistry.get()
        .filter((state: Ng2StateDeclaration) => !!state.loadChildren)
        .forEach((state: Ng2StateDeclaration) => {
            // JiT
            if (typeof state.loadChildren === 'function') {
                state.loadChildren();
            }
            // AoT
            else if (typeof state.loadChildren === 'string') {
                // Ignore the returned promise as we don't care when it loads, as long as the loading process has
                // been initialised, it will load eventually.
                loader.load(state.loadChildren);
            }
    });
    deregisterPreloadLazyLoadedRouteHook();
});
```
