### ISSUE TITLE
Angular 4 - Using Route Guards

### ISSUE THREAD

**Issue by phanivaranasi** [ui-router/angular#257]
Hi,
We are using Angular5 with UI Router 2
In earlier version of UI Router we have OnExit  - OnEnter params etc.
But in new version where I can implement these sort of functions and also I need guidance in implementing Route guards with UI Router.

Thanks in Advance.

**Comment by christopherthielen** [comment]
Most of what you remember from UI-Router for AngularJS also works with Angular2+.

`onExit` and `onEnter` are still supported [docs](https://ui-router.github.io/ng2/docs/latest/interfaces/state.ng2statedeclaration.html#onenter) but do not get injected like in AngularJS.  Instead, you can use something like `transition.injector().get(MyService)`.

```ts
export const MyState = {
  name: 'mystate',
  url: '/mystate',
  component: MyComponent,
  onExit: onExitFn,
}

export function onExitFn(transition: Transition, state: Ng2StateDeclaration) {
  console.log('Exiting ' + state.name);
}
```

Transition Hooks are what we call the ui-router equivalent to route guards.  Read [the guide on Transition Hooks](https://ui-router.github.io/guide/transitionhooks) and examine the Sample App (in particular, the [Requires Auth Hook](https://github.com/ui-router/sample-app-angular/blob/671fdebf7475087930c1dc4d039a6c16b5231668/src/app/global/auth.hook.ts))

```ts
transitionService.onStart({ to: 'parent.**' }, transition => {
  const injector = transition.injector();
  const $state: StateService = transition.router.stateService;
  if (injector.get(SomeService).checkAThing()) {
    return $state.target('login'); // redirect to login
  }
});
```

UI-Router for Angular also has Observables for state transitions and/or parameter changes:

-  `router.globals.success$.subscribe(...)`
-  `router.globals.params$.subscribe(...)`
