### ISSUE TITLE
@angular/router vs @uirouter/angular

### ISSUE THREAD

**Issue by kolkov** [ui-router/angular#289]
Dear sirs, someone of those who use both can make a more or less detailed comparison, indicating the strengths of each of the software products?
Thanks!

**Comment by lgaitan** [comment]
Hi, 

I guess this is a pretty good article even though it refers to AngularJS.
[UI-Router: Why many developers don’t use AngularJS’s built-in router](http://www.funnyant.com/angularjs-ui-router/)

Also to mention, UI-Router is basically the same for both Angular and AngularJS.

**Comment by wawyed** [comment]
Have a look at :

https://github.com/ui-router/core#features
