### ISSUE TITLE
Lazy loading and AOT, factory.create is not a function

### ISSUE THREAD

**Issue by mtraynham** [ui-router/angular#298]
I am lazy loading a child module like below:

```ts
export function lazyLoad (transition: Transition, stateObject: StateDeclaration): Promise<LazyLoadResult> {
    return loadNgModule(() => import('./app.module')
        .then(({AppModule}: any) => AppModule))(transition, stateObject);
}

export const states: Ng2StateDeclaration = [
    {
        name: 'index.app.**',
        url: '/',
        lazyLoad
    }
];
```

In JIT mode this seems to run fine, but in AOT, I'm getting the following exception:
```
stateService.js.pre-build-optimizer.js?90d2:43 TypeError: factory.create is not a function
    at createModule (lazyLoadNgModule.js?0395:50)
    at ZoneDelegate.invoke (zone.js?b979:388)
    at Object.onInvoke (core.js.pre-build-optimizer.js?4978:4760)
    at ZoneDelegate.invoke (zone.js?b979:387)
    at Zone.run (zone.js?b979:138)
    at eval (zone.js?b979:872)
    at ZoneDelegate.invokeTask (zone.js?b979:421)
    at Object.onInvokeTask (core.js.pre-build-optimizer.js?4978:4751)
    at ZoneDelegate.invokeTask (zone.js?b979:420)
    at Zone.runTask (zone.js?b979:188)
$defaultErrorHandler @ stateService.js.pre-build-optimizer.js?90d2:43
```

**Comment by ViieeS** [comment]
@mtraynham did you solve this?

**Comment by mtraynham** [comment]
Nope 😕 I ran out of time experimenting with it.  I actually use Angular Router now with success in lazy loading routes and AOT, but I imagine that won’t help you much.

**Comment by ViieeS** [comment]
@mtraynham yeah... AOT works fine with ui-router, but I don't get why dynamic import doesn't.

**Comment by scipper** [comment]
@mtraynham Lazy Loading is kind of picky regarding to the syntax. I guess using an exported function does not work. For me, the **exact syntax** and **formation** like this did the trick: 
`loadChildren: () => import('./custom/custom.module').then(m => m.CustomModule)` (respect the single quotes!, one line!, and no curly braces and returns!)

This is also AOT comform, as it is described this way in the [UI-Router docs](https://ui-router.github.io/ng2/docs/latest/interfaces/state.statedeclaration.html#lazyload) (although it is called lazyLoad 🤔)

It is described here: https://github.com/angular/angular-cli/issues/10582
