### ISSUE TITLE
Getting "Cannot read property 'STATE' of undefined" Angular 6

### ISSUE THREAD

**Issue by shyamal890** [ui-router/angular#302]
After upgrading to Angular 6 `ng serve` works alright but `ng serve --prod` doesn't, gives following error:

> Cannot read property 'STATE' of undefined

```
transitionService.js:180 Uncaught TypeError: Cannot read property 'STATE' of undefined
    at e._defineCorePaths (transitionService.js:180)
    at new e (transitionService.js:73)
    at new e (router.js:62)
    at _ (providers.js:113)
    at core.js:9214
    at xo (core.js:9168)
    at core.js:9099
    at new e (core.js:9817)
    at Object.Jo [as createNgModuleRef] (core.js:9806)
    at n.create (core.js:12337)
```

**Comment by shyamal890** [comment]
@christopherthielen can you please have a look at this.

Attaching a demo project for reference. Just run `ng serve --prod` and it will give the above error

[test.zip](https://github.com/ui-router/angular/files/1978937/test.zip)

**Comment by schmitch** [comment]
actually this only happens when `--build-optimizer=true` (the default since angular 5 or 6)

**Comment by christopherthielen** [comment]
I’ve filed this issue https://github.com/angular/angular/issues/23759

We can probably fix this in uirouter/core by changing how we export the enum

**Comment by christopherthielen** [comment]
Fixed by https://github.com/ui-router/core/commit/38d25faf6adffe51b87208f4bbd2b955cb05754d
