### ISSUE TITLE
Angular breadcrumb component based on @uirouter/angular

### ISSUE THREAD

**Issue by Toskv** [ui-router/angular#334]
Hey,

I'm migrating an AngularJs application that uses angular-ui-router 0.3.1 for routing to Angular.
The app uses a breadcrumb that was built on top of [angular-utils-ui-breadcrumbs](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/uiBreadcrumbs). 

It has a couple properties that are nice, like building breadcrumbs from the parent states of the current state and being able to interpolate resolved values from a state as breadcrumb texts.

I tried looking for something similar for the current version of ui-router but I just can't seem to find one. Actually I can't seem to find any breadcrumb components for ui-router/angular.

I also tried building my own but the furthest I got was subscribing to the transition service and getting the current state. From there I the only way I see to get the resolved values would be by using the transition.getResolveTokens() and transition.injector().get().

Even so though that seems only to work from the states that particular transition goes 'from' and 'to'. I didn't find a way to retrieve the resolve tokens for any other parents states.

Is this the way to go?
Does anyone know of a breadcrumb component for the current version?

**Comment by christopherthielen** [comment]
Here's a simple breadcrumb component: 

```ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { UIRouter, PathNode, Transition } from '@uirouter/core';
import { Subject } from 'rxjs';

// Add `breadcrumb` to typescript definitions for StateObject and StateDeclaration
declare module "@uirouter/core/lib/state/stateObject" {
  interface StateObject {
    breadcrumb?: (trans: Transition) => string;
  }
}

declare module "@uirouter/core/lib/state/interface" {
  interface StateDeclaration {
    breadcrumb?: (trans: Transition) => string;
  }
}

interface Crumb {
  state: string;
  text: string;
}

// This is a home component for authenticated users.
// It shows giant buttons which activate their respective submodules: Messages, Contacts, Preferences
@Component({
  selector: 'app-breadcrumbs',
  template: `
    <ul class="breadcrumbs">
      <li *ngFor="let crumb of crumbs">
        <a [uiSref]="crumb.state">{{crumb.text}}</a>
      </li>
    </ul>
  `,
  styles: [`
    .breadcrumbs { list-style: none; }
    ul li { display: inline; }
    li + li:before { content: '/'; padding: 1em; }
  `]
})
export class BreadcrumbsComponent implements OnDestroy {
  private unsub: any;
  private crumbs: Crumb[] = [];

  constructor(public router: UIRouter) {
    this.updateCrumbs(router.globals.successfulTransitions.peekTail())
    this.unsub = router.transitionService.onSuccess({}, trans => this.updateCrumbs(trans));
  }

  private updateCrumbs(trans: Transition) {
    this.crumbs = trans.treeChanges('to')
      .filter(node => node.state.breadcrumb)
      .map(node => {
        return { 
          state: node.state.name, 
          text: node.state.breadcrumb(trans)
        }
      });
  }

  ngOnDestroy() {
    this.unsub();
  }
}
```

And I added to the sample app: https://stackblitz.com/edit/ui-router-sample-app-angular-breadcrumbs?file=src%2Fapp%2Fbreadcrumbs.component.ts

The idea is to listen for successful transitions, get the newly activated path (the "to" path), check each state for a `breadcrumb` function, run each function, render the list of results as `uiSref`.

Hope this helps!
