### ISSUE TITLE
FEATURE REQUIRED: Implementing "window.onpopstate = funcRef;"

### ISSUE THREAD

**Issue by paulodrade** [ui-router/angular#353]
Would be possible to implement something like `window.onpopstate = funcRef`? It would very nice if `ui-router` could listening to it and we would just do a `pushState()` to deal with URL changes for nested lazy load module states.

As @bouncehead13 reported very well on #164 , this is a very bad SEO indexing problem. 

> The problem is the href gets set as href="/shop" instead of href="/shop/product/product-slug". I know this is because the lazy loaded routes have not been loaded yet so it doesn't know what to resolve. However, this is a major bug because SEO bots cannot crawl the homepage because all links point to just /shop. In addition, right-click and open link in a new tab opens to /shop. Both cases should link to the fully built url (href="/shop/product/product-slug").

**Comment by nateabele** [comment]
> I know this is because the lazy loaded routes have not been loaded yet

This sounds like a server-side rendering problem.

**Comment by paulodrade** [comment]
@nateabele This is not a server-side rendering...

`ui-router` just work with `StateService.go()` or `uiSref=""`. There is no other way to trigger a state. This became an issue because of lazy loading module (and its states consequently).

If `ui-router` listening for `onpopstate` trigger, I think it would solve the problem because then we could deal with `pushState` ourselves.
