### ISSUE TITLE
Hybrid app (ng1+ng2)

### ISSUE THREAD

**Issue by BenevidesLecontes** [ui-router/angular#38]
HI! Guys, Thank you for your amazing work. In my company we are building a large app with angular 1 + ui-router, but we've decided to upgrade to angular 2. We already bootstrapped the angular 1 app, everything is running as supposed, but we're facing some troubles to route ng2 components with ui-router for ng2. Can someone give the light?

This is my bootstrap 
```
 * Create our upgradeAdapter
 */
const upgradeAdapter: UpgradeAdapter = new UpgradeAdapter(
  forwardRef(() => WiseitAppModule));

/*
 * Expose our ng1 content to ng2
 */
uiRouterNgUpgrade.setUpgradeAdapter(upgradeAdapter);
upgradeAdapter.upgradeNg1Provider('$state');
@NgModule({
  declarations: [
    HelloWorldComponent
  ],
  imports: [
    CommonModule,
    BrowserModule,
    FormsModule,
    Ng1ToNg2Module,
    UIRouterModule.forRoot({ states:  [helloState], useHash: true,})
  ],
  providers: []
})
export class WiseitAppModule {
}


/*
 * Bootstrap the App
 */
upgradeAdapter.bootstrap(document.documentElement, ['wiseit'], {strictDi: false});

```

This is my test route
```
export const helloState = {
  name: 'hello',
  url: '/hello-world',
  component: HelloWorldComponent
};
```

**Comment by christopherthielen** [comment]
ng1-to-ng2 needs an update. right now it's stuck on an older version of angular2

I'm working on a new release of ui-router-ng2 and then the sample-app-ng2, then I'm going to update ng1-to-ng2.  The bootstrapping will probably be somewhat different from the current version.

**Comment by BenevidesLecontes** [comment]
@christopherthielen thanks for the answer, i will wait until then. For now did you have a temporary solution for me to route my ng2 components based on ng1 routes?

**Comment by christopherthielen** [comment]
Related issue: https://github.com/ui-router/ng2/issues/49

**Comment by christopherthielen** [comment]
@BenevidesLecontes you can use the ng1 only router, and route to downgraded components using a route-to-component template like
```
template: `<my-downgraded-ng2-component></my-downgraded-ng2-component>`

**Comment by BenevidesLecontes** [comment]
@christopherthielen I'm sorry, but i didn't get your tip, You're saying to me to downgrade my ng2 components and use ng1 router?

**Comment by amcdnl** [comment]
@BenevidesLecontes  - Check out https://github.com/swimlane/ng1-ng2-webpack-lazy-uirouter

**Comment by BenevidesLecontes** [comment]
@amcdnl Thanks, I already did it.

**Comment by christopherthielen** [comment]
Closing since https://github.com/ui-router/angular-hybrid is ready
