### ISSUE TITLE
Problem with the UiRouterModule when building with --aot --watch

### ISSUE THREAD

**Issue by jeroenvheel** [ui-router/angular#422]
Hi guys,

We have a problem with the UiRouterModule when building with --aot --watch
after saving changes to a component the cli will try to build the project and will run into this issue

```
 ERROR in Illegal State: external references changed in 
 C:/DataQuint/geo-bag/GeoBAG.Online/GeoBAG/src/app/Shared/Shared.Components.Module.ngfactory.ts.
 
 Old: 
 @angular/core,
 ./Shared.Components.Module,
 @uirouter/angular/lib/directives/uiSref,
 @uirouter/angular/lib/directives/uiView,
 @uirouter/angular/lib/directives/uiSrefActive,
 @uirouter/angular/lib/directives/uiSrefStatus,
 @angular/common,
 ./Components/Header/Header.Component,
 ./Components/HeaderMenu/HeaderMenu.Component,
 ./Components/ModalPopup/ModalConfirm.Component,
 @uirouter/angular/lib/uiRouterNgModule,
 @angular/platform-browser,
 ../GeoVisia/GeoVisia.Components.Module.
 
 New: 
 @angular/core,
 ./Shared.Components.Module,
 @uirouter/angular/lib/directives/uiSref,
 @uirouter/angular/lib/directives/uiView,
 @uirouter/angular/lib/directives/uiSrefActive,
 @uirouter/angular/lib/directives/uiSrefStatus,
 @angular/common,
 ./Components/Header/Header.Component,
 ./Components/HeaderMenu/HeaderMenu.Component,
 ./Components/ModalPopup/ModalConfirm.Component,
 @uirouter/angular,
 @angular/platform-browser,
 ../GeoVisia/GeoVisia.Components.Module
```
as you can see in the old the reference to the UIRouterModule is
 ### @uirouter/angular/lib/uiRouterNgModule,
and after the change
###  @uirouter/angular,

how can i resolve this issue ?

**Comment by mkoczorowski** [comment]
remove npm modules directory, then run npm cache clean -f and npm install again

**Comment by cthrax** [comment]
@mkoczorowski I tried removing npm modules directory and clearing cache to no effect. I am running versions:
@angular: 7.0.3
@ui-router/angular: 2.0.2

Any other thoughts or @jeroenvheel did you come up with a solution?

**Comment by adam-marshall** [comment]
Encountered this now, any workaround @jeroenvheel / @cthrax ?

**Comment by cthrax** [comment]
@adam-marshall sticking with the previous version.

**Comment by adam-marshall** [comment]
> @adam-marshall sticking with the previous version.

Sorry @cthrax, I am not sure what you mean. Did you downgrade back to a particular version of `@uirouter/angular`? I'm using 4.0.0.

**Comment by cthrax** [comment]
Ack, I'm sorry @adam-marshall I thought this was a different issue I'm following.

I have not found a solution to this issue, other than not watching with aot. Standard watch works fine.

**Comment by christopherthielen** [comment]
All, please let us know if upgrading to Angular 9 and the latest UI-Router solves this issue

**Comment by ronyf** [comment]
Anything? How can we solve this?

**Comment by jeroenvheel** [comment]
I switched using the angular router.
I was only using the ui-router because I’m using multiple router outlets but I found a way to do this with the angular router.

**Comment by ronyf** [comment]
@jeroenvheel can you please post your workaround?
