### ISSUE TITLE
Angular 7 compatibility?

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [ui-router/angular#423]
npm warns:
```
npm WARN @uirouter/angular@2.0.2 requires a peer of @angular/common@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
```

But is there anything in 7.0 that would break ui router? Do we wait for some kind of compatibility fixes/patch, or is it just matter of updating the package dependency version?

**Comment by oliverguenther** [comment]
uirouter appears to rely on the `rxjs-compat` in several legacy imports so an upgrade to 7.0. will not work without addressing it.

```
ERROR in ./node_modules/@uirouter/angular/lib/directives/uiSrefStatus.js
Module not found: Error: Can't resolve 'rxjs/BehaviorSubject' in 'app/frontend/node_modules/@uirouter/angular/lib/directives'
ERROR in ./node_modules/@uirouter/angular/lib/directives/uiSref.js
Module not found: Error: Can't resolve 'rxjs/ReplaySubject' in 'app/frontend/node_modules/@uirouter/angular/lib/directives'
ERROR in ./node_modules/@uirouter/rx/lib-esm/ui-router-rx.js
Module not found: Error: Can't resolve 'rxjs/ReplaySubject' in 'app/frontend/node_modules/@uirouter/rx/lib-esm'
ERROR in ./node_modules/@uirouter/rx/lib-esm/ui-router-rx.js
Module not found: Error: Can't resolve 'rxjs/add/operator/map' in 'app/frontend/node_modules/@uirouter/rx/lib-esm'
ERROR in ./node_modules/@uirouter/rx/lib-esm/ui-router-rx.js
Module not found: Error: Can't resolve 'rxjs/add/operator/mergeMap' in 'app/frontend/node_modules/@uirouter/rx/lib-esm'
ERROR in ./node_modules/@uirouter/angular/lib/directives/uiSrefStatus.js
Module not found: Error: Can't resolve 'rxjs/observable/combineLatest' in 'app/frontend/node_modules/@uirouter/angular/lib/directives'
ERROR in ./node_modules/@uirouter/angular/lib/directives/uiSrefStatus.js
Module not found: Error: Can't resolve 'rxjs/observable/fromPromise' in 'app/frontend/node_modules/@uirouter/angular/lib/directives'
ERROR in ./node_modules/@uirouter/angular/lib/directives/uiSrefStatus.js
Module not found: Error: Can't resolve 'rxjs/observable/of' in 'app/frontend/node_modules/@uirouter/angular/lib/directives'
ERROR in ./node_modules/@uirouter/angular/lib/directives/uiSrefStatus.js
Module not found: Error: Can't resolve 'rxjs/operator/concat' in 'app/frontend/node_modules/@uirouter/angular/lib/directives'
ERROR in ./node_modules/@uirouter/angular/lib/directives/uiSrefStatus.js
Module not found: Error: Can't resolve 'rxjs/operator/map' in 'app/frontend/node_modules/@uirouter/angular/lib/directives'
ERROR in ./node_modules/@uirouter/angular/lib/directives/uiSrefStatus.js
Module not found: Error: Can't resolve 'rxjs/operator/switchMap' in 'app/frontend/node_modules/@uirouter/angular/lib/directives'
```

**Comment by sebastian-zarzycki-es** [comment]
Just to make sure, are you saying that it works without rxjs-compat? I've noticed that as soon as I'll drop it, it breaks (states not switching, etc.).

**Comment by oliverguenther** [comment]
@sebastian-zarzycki-es As far as I can tell, yes. It is running fine on our development branch. OpenProject has a fairly large frontend with a significant number of integration tests, so switching between states definitely works.

**Comment by sebastian-zarzycki-es** [comment]
It's working ok for me too. I've experiences some weird behavior due to my own code, not router's. I guess new release with dependencies bumped would be nice.

**Comment by BARTlab** [comment]
Is there any news about the update?

**Comment by deonclem** [comment]
Any update on this ? ng7 has been out for 2 months now.

**Comment by ngehlert** [comment]
Any new updates on this? Is this lib still maintained? Looks like everyone "jumped the ship"?
Is there a simple way to migrate from ui-router to native angular router? Whats the best approach for hybrid apps that use the ui-hybrid-router? They can't really rely on the Angular router...

**Comment by deonclem** [comment]
@christopherthielen Any insights on the comment above would be appreciated 🙂

**Comment by christopherthielen** [comment]
I'm still maintaining this lib.  I've already triaged this as High priority.  It's up next.

**Comment by christopherthielen** [comment]
Also, sorry for the delay in ng7 support.  I've haven't had much time to devote to OSS lately.

**Comment by tommck** [comment]
@christopherthielen you mean you need a pay check to survive? O_O

**Comment by christopherthielen** [comment]
https://github.com/ui-router/angular/releases/tag/3.0.0

**Comment by ngehlert** [comment]
@christopherthielen  thanks for this new version. can you please also update the hybrid router package to also support angular 7?
