### ISSUE TITLE
Angular Universal w /Dotnet core reports window not found

### ISSUE THREAD

**Issue by NelsonLamprecht** [ui-router/angular#43]
Exception: Call to Node module failed with error: ReferenceError: window is not defined
 at Ng2LocationServices.BaseLocationServices 
 at new Ng2LocationServices 
 at uiRouterFactory 

Has anyone gotten ui-router-ng2 to work with angular-universal. 
It appears to have a requirement on the DOM?

**Comment by aitboudad** [comment]
you should use `MemoryLocationService` + `MemoryLocationConfig` in `node.module.ts`:

```ts
import { UIRouterModule, UIRouter, MemoryLocationService, MemoryLocationConfig } from 'ui-router-ng2';
import { LocationStrategy, PlatformLocation } from '@angular/common';

export class MainModule {
  constructor(public cache: CacheService, router: UIRouter, locationStrategy: LocationStrategy) {
    router.locationConfig = new MemoryLocationConfig();
    router.locationService = new MemoryLocationService(router);
    router.locationService['_url'] = locationStrategy.path(true);
  }
}
```

**Comment by aitboudad** [comment]
And if you use lazyLoad try to use `APP_INITIALIZER` https://github.com/ui-router/ng2/issues/18#issuecomment-278979039

**Comment by christopherthielen** [comment]
Closing because I think this is resolved by https://github.com/ui-router/angular/issues/43#issuecomment-278976233

**Comment by mchambaud** [comment]
I'm having similar issue but for `document`. Any ideas?
