### ISSUE TITLE
No states are loaded when using aot

### ISSUE THREAD

**Issue by jensengar** [ui-router/angular#431]
I've been developing an app without aot. I recently tried to switch it over to aot and it results in a blank page when loading the app. There are no build errors and no console errors. What's interesting is no routes are loaded in uirouter when using `--aot`. see the following console output when using aot:

![image](https://user-images.githubusercontent.com/6035507/48331337-0f45dc00-e60d-11e8-9dec-50bd9f4c4a77.png)

but when not using aot:

![image](https://user-images.githubusercontent.com/6035507/48331510-8bd8ba80-e60d-11e8-821b-008325a9564d.png)

My module imports looks like this so there *should* be routes and a "otherwise" defined:
```
  imports: [
    BrowserModule,
    UIRouterModule.forRoot({
      states,
      otherwise: { state: 'nl.index' },
      config: routerConfigFn,
    }),
    ...
```

I know there's tons of people using ui-router with aot so there's obviously something specific to my setup but I wouldn't even know where to begin to look since there are no errors in the build or console. Do you have any suggestions?

**Comment by jensengar** [comment]
I was finally able to track down the problem. I'm not sure why it matters and would be interested to know. I had put all my routes in a separate file, then imported them into app.module to pass them into UIRouterModule. For some reason, importing the routes from a different file screws things up when using aot. I can take the same route/state declarations and load them directly without any issues. I've also console logged the imported version and the "direct" version and as far as I can tell they are identical.

**Comment by aserraric** [comment]
I have the same problem. Looking at the compiled Javascript, the AOT compiler completely removes the "states" property from the config object, unless it is completely defined inline:

`{
      states: APP_STATES,
      useHash: false,
      otherwise: { state: 'home' },
      config: routerConfigFn
    }`
becomes 
`{
  useHash: !1,
  otherwise: {
    state: "home"
  },
  config: py
}`

And even when I try to define one state inline and then concat the imported states to it, everything is discarded.

**Comment by aserraric** [comment]
I have now found a workaround: The import works as long as the states collection is a const array of exported consts.
If there is more than one collection, they have to be combined with the spread operator (.concat() will not work).

states.ts:
```
export const homeState: Ng2StateDeclaration = {
  name: 'home',
  url: '/',
  component: HomeComponent,
}

export const STATES = [homeState];
```
app.module.ts
```
import { STATES } from './states.ts';
import { OTHER_STATES } from './other_states.ts';
...
imports: [
    UIRouterModule.forRoot({
      states: [...STATES, ...OTHER_STATES],
      useHash: false,
      otherwise: { state: 'home' },
      config: routerConfigFn
    }),
...
```

**Comment by Xen3r0** [comment]
Did you used Array.concat for your states ?

**Comment by aserraric** [comment]
As I've said, Array.concat() does not work, the array has to be const at AOT compile time.

**Comment by Xen3r0** [comment]
Yes i see now :) Why concat isn’t work ? I don’t understand this problem. Nobody have an answer ?

**Comment by wileymarques** [comment]
AOT only supports a subset of JS, which can be found [here](https://angular.io/guide/aot-compiler#expression-syntax).

This may be the problem you are facing.

**Comment by aserraric** [comment]
I guess this makes sense, and it probably the reason my method works: The array of state definitions has to remain a literal throughout. I'm just confused as to why the AOT compiler silently drops the property instead of generating an error if it isn't.

**Comment by wawyed** [comment]
> 
> 
> AOT only supports a subset of JS, which can be found [here](https://angular.io/guide/aot-compiler#expression-syntax).
> 
> This may be the problem you are facing.

I believe this can ble closed as it's based on AOT restrictions and not do to with ui-router itself.
