### ISSUE TITLE
UIrouter compile error with Angular Ivy

### ISSUE THREAD

**Issue by jr01** [ui-router/angular#516]
Hi!

When using Angular Ivy compiler `ng build --prod` fails with

> ERROR in src/app/app.module.ts(12,12): error TS-991010: Value at position 1 in the NgModule.importss of AppModule is not a reference: [object Object]

The ivy-ngcc compiler gives some warnings that could be related:
> Compiling @uirouter/core : module as esm5
> Warning: Unknown member type: "[key: string]: any;
> Compiling @uirouter/angular : module as esm5
> Warning: Unknown member type: "[key: string]: any;

Here is a github repo to reproduce the issue [uirouterivy](https://github.com/jr01/uirouterivy) and this [commit](https://github.com/jr01/uirouterivy/commit/9807699fd63a4ac10814d5204046f44fded3787a) is all that was done on top of a `ng new uirouterivy` .
Steps to reproduce the issue:
```
git clone https://github.com/jr01/uirouterivy
cd uirouterivy
npm install
ng build --prod
```

It works fine w/o Angular Ivy:
```
git checkout 456833
ng build --prod
```

**Comment by jam2z9** [comment]
I'm experiencing the same thing when importing a non angular module into app.module.

**Comment by zhangxiang93** [comment]
Same problem

**Comment by mkoczorowski** [comment]
same here

**Comment by christopherthielen** [comment]
Thank you for this issue with clear reproduction steps.  I will take a look this weekend!

**Comment by pradeepsrawat029** [comment]
hi  same problem here. angular 8 ivy compiler 
Value at position 2 in the NgModule.importss of AppModule is not a reference: [object Object]

**Comment by christopherthielen** [comment]
I played around with this a bit over the weekend.  I think the solution to this may be to use [`ng-packagr`](https://github.com/ng-packagr/ng-packagr) to create a npm package that conforms to the [angular package format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#!).

This may require a break in compatibility with Angular v5 but that's OK.  We would need another major release of ui-router for Angular (version 5.0.0)

**Comment by christopherthielen** [comment]
update: I was able to build the package using ng-packagr and added ui-router to a brand new "`ShinyIvyApp`".  However, I ran into troubles trying to update the `sample-app-angular` to use ivy.

**Comment by oBusk** [comment]
> update: I was able to build the package using ng-packagr and added ui-router to a brand new "`ShinyIvyApp`". However, I ran into troubles trying to update the `sample-app-angular` to use ivy.

What issues did you have? Got the WIP somewhere?

**Comment by mkoczorowski** [comment]
@christopherthielen do we have any progress on this issue ? Angular 9 is round the corner which is ivy. It would be a real shame we ui-router cannot support this.

**Comment by christopherthielen** [comment]
here's the branch with ng-packagr support

https://github.com/ui-router/angular/compare/ng-packagr?expand=1

To test this locally, I'm using https://github.com/whitecolor/yalc as a local package publisher. 
```
yarn global install yalc
```

Build `@uirouter/angular` locally using `ng-packagr`:
```
npx ng-packagr -p package.json
```

Now add it to your downstream app using yalc.  
```
cd <myangularapp>
yalc add @uirouter/angular
yarn install
```

Yarn will complain about missing peer dependencies, so also add the two upstream uirouter dependencies.
```
yarn add @uirouter/rx@0.5.0
yarn add @uirouter/core@5.0.23
```

**Comment by jr01** [comment]
so I just tried the ng-packagr branch with Angular Ivy in a large angular-hybrid app and it seems to work 👍 

I added the ng-packagr branch in `package.json`, here is a snippet of the @uirouter bits I have in there:
```
    "@uirouter/core": "5.0.23",
    "@uirouter/angular": "ui-router/angular#ng-packagr",
    "@uirouter/angular-hybrid": "8.0.0",
```

and of course I enabled Ivy like I did in the initial post [^^](https://github.com/ui-router/angular/issues/516#issue-434616499)

Many thanks @christopherthielen 🥇

**Comment by jr01** [comment]
So I tried the [ng-packagr branch](https://github.com/ui-router/angular/compare/ng-packagr?expand=1) with the app from my [initial post](https://github.com/ui-router/angular/issues/516#issue-434616499)  and I got it to work.

Here is what I did:

For @uirouter/angular
- `git clone https://github.com/ui-router/angular .` in folder `C:\custom_npm\@uirouter\angular`
- `git checkout ng-packagr`
- `npm install`
- `ng-packagr -p package.json`

For the app
- Get the app: `git clone https://github.com/jr01/uirouterivy .`
- Update Angular to v8 latest: `ng update @angular/cli @angular/core rxjs`
- Remove node_modules folder: `rd /s/q node_modules`
- `npm install`
- Modified package.json
```
    "@uirouter/core": "5.0.23",
    "@uirouter/rx": "0.5.0",
    "@uirouter/angular": "C:/custom_npm/@uirouter/angular/dist",
```
- Modified angular.json
	set `"preserveSymlinks": true,` as suggested [here](https://github.com/angular/angular/issues/25813#issuecomment-440288681)	

- `ng serve` works :-)
- Applied some of the @uirouter/angular Hello World example and confirmed some simple routing works :-)

Here is my ng-packagr testing branch for the app: https://github.com/jr01/uirouterivy/compare/ng-packagr?expand=1

I'll do some more testing, final goal is to get an ngupgrade + @uirouter/angular-hybrid application to work with Angular 9.

Many thanks so far @christopherthielen 🥇

**Comment by dannyskoog** [comment]
@jr01 That sounds great!

Btw - you state that you used latest Angular 8. Why not latest beta (`9.0.0-next.6`)?

**Comment by dannyskoog** [comment]
@christopherthielen Would you by any chance have a rough idea of when an Ivy compatible version 5 of UI Router could be released? (i.e. october/november versus later)

**Comment by christopherthielen** [comment]
I've made [more some progress](https://github.com/ui-router/angular/tree/ivy)

I'm not going to make any promises on timing of an ivy compatible release, but things are looking pretty good

**Comment by dannyskoog** [comment]
I’m more than fine with that answer @christopherthielen. Sounds good and thanks for your hard (and appreciated) work!

**Comment by christopherthielen** [comment]
Looks like we'll be dropping support for Angular versions 7 and below.  I was surprised to learn that Angular 8 (without ivy) is also able to lazy load without the `ROUTES` token from `@angular/router` (i.e., this got fixed https://github.com/angular/angular-cli/issues/9343)

**Comment by mgechev** [comment]
Hi @christopherthielen, is there anything else blocking you from releasing the Ivy compatible version? We'll be happy to help if there's anything we can do!

**Comment by christopherthielen** [comment]
@mgechev thanks for reaching out!  I think code-wise, ui-router ivy branch is ready to release.  I just want to update docs and examples first.

**Comment by christopherthielen** [comment]
Released v6.0.0 https://github.com/ui-router/angular/releases/tag/6.0.0

**Comment by petebacondarwin** [comment]
Great @christopherthielen - can you release `@uirouter/angular-hybrid` too? Currently that is pinned to use `@uirouter/angular@5` so it is still broken with ivy.

**Comment by wawyed** [comment]
@petebacondarwin I'm working on updating it.

**Comment by christopherthielen** [comment]
published https://github.com/ui-router/angular-hybrid/releases/tag/10.0.0

**Comment by oBusk** [comment]
I'm getting 

```
Compiling @uirouter/core : main as commonjs
Compiling @uirouter/core : module as esm5
Compiling @uirouter/angular : fesm2015 as esm2015
Warning: Unknown member type: "[key: string]: any;
Compiling @uirouter/angular : fesm5 as esm5
Compiling @uirouter/angular : esm2015 as esm2015
Compiling @uirouter/angular : esm5 as esm5
Compiling @uirouter/angular : main as umd
Compiling @uirouter/angular-hybrid : fesm2015 as esm2015
No suitable injection token for parameter 'ref' of class 'UIViewNgUpgrade'.
no type or decorator
```

when running `ivy-ngcc` with versions

```
"@uirouter/angular": "^6.0.1",
"@uirouter/angular-hybrid": "^10.0.0",
"@uirouter/angularjs": "^1.0.23",
"@uirouter/core": "^6.0.1",
"@uirouter/rx": "^0.6.4",
```

**Comment by petebacondarwin** [comment]
@oBusk - if you are using `ivy-ngcc` then you must be on an older version of Angular. Can you try with the most recent (`yarn add @angular/compiler-cli@next`, etc) - in which case the binary is now called `ngcc`. If it still erroring, let me know and I will look into it.

**Comment by oBusk** [comment]
@petebacondarwin Oh! Thanks for that! I had an outdated branch for ivy.

I got rid of that, got further, but now running into 
```
ERROR in Symbol UIRouterModule declared in C:/MY_PROJECT/node_modules/@uirouter/angular/uiRouterNgModule.d.ts is not exported from @uirouter/angular-hybrid (import into C:/MY_PROJECT/src/app/cool-module/cool-module.module.ts)
```

I don't see any other option for importing `UIRouterUpgradeModule` from angular-hybrid? 
I created an issue for it (https://github.com/ui-router/angular-hybrid/issues/381), seems off-topic for this issue.

**Comment by wawyed** [comment]
What are the contents of cool-module.module.ts ?

**Comment by oBusk** [comment]
@wawyed The issue was that I was not using angular v9 release candidate which is required to run ivy with `@uirouter/angular-hybrid`. See https://github.com/ui-router/angular-hybrid/issues/381#issuecomment-559276597 

However `@uirouter/angular-hybrid` has another issue; https://github.com/ui-router/angular-hybrid/issues/382
