### ISSUE TITLE
in latest Angular 7, useHash: true stopped working

### ISSUE THREAD

**Issue by httpete** [ui-router/angular#517]
I only have one app I run with the old hash, but it stopped working.

**Comment by httpete** [comment]
In order to fix this, I had to do this in the providers of my top level module. It used to work with useHash true on my forRoot() config just fine.

    { provide: LocationStrategy, useClass: HashLocationStrategy }

**Comment by coolblades** [comment]
the above suggestion worked in restoring # in my url but has side effect of this angular error:
core.js:4002 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'admin'
Error: Cannot match any routes. URL Segment: 'admin'

as if it is try to use angular router

**Comment by stnor** [comment]
Looking at @httpete's workaround I'm thinking #707 is the same issue.

**Comment by coolblades** [comment]
ok got past the angular error by not doing this in app module - imports section:
RouterModule.forRoot([])

And then remove import of Location 
import { Location } from '@angular/common';

So I don't need the workaround mentioned here either.

**Comment by adelamera** [comment]
I got this error, too. I tried using { provide: LocationStrategy, useClass: HashLocationStrategy }, but it's still not working.

**Comment by christopherthielen** [comment]
FWIW, the sample app uses `useHash: true` and it seems to work.  I have no idea what was going on to cause this issue.
