### ISSUE TITLE
Component constructor called twice upon state.go(...)

### ISSUE THREAD

**Issue by Louis012** [ui-router/angular#529]
My configuration : 

- Angular 4 project
- @uirouter/angular: **1.1.0**

Hi,

I am using ui-router in my app, it works perfectly expected for one specific configuration.
When I call : 

` this.stateService.go(
            'my_component', {
                myParam: "some|param" // <-- Note the pipe symbol here
            }
        );`

When `MyComponent` gets loaded, the constructor is called **twice**.
However, if I simply reload the page (so that I do not call `stateService.go(...)`, the constructor is called only once as expected.

This problem happens only if there is a pipe symbol in one of my parameters.

I believe this could be caused by an error inside ui-router, happening during the change detection (https://stackoverflow.com/a/38787863/6114088).

I cannot bump my ui-router/angular version because the project I work on is using Angular 4.

Any thought on this behavior ? Is the pipe symbol not supported ?

**Comment by christopherthielen** [comment]
Hi from the future.  The pipe symbol is supported by the router in a parameter value.  

Is this still an issue for you?  Based on the linked stackoverflow, it sounds like this can happen if the template has any syntax problems (i.e., missing a closing tag `<my-comp><my-comp>`).  I would check the template for `MyComponent` for any syntax errors.  

I would also try enabling the ui-router trace feature and see if there are two *state changes* happening that would cause the component to get mounted twice.  
```
uirouter.trace.enable(1)
```

**Comment by Louis012** [comment]
I am no longer working on this project, sorry :(

**Comment by christopherthielen** [comment]
thanks for responding!
