### ISSUE TITLE
Update to angular 8

### ISSUE THREAD

**Issue by jpike88** [ui-router/angular#543]
```@uirouter/angular@3.0.0 requires a peer of @angular/common@^5.0.0 || ^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.```

**Comment by oliverguenther** [comment]
I opened a PR here to create tests for 8.0.0, looks like no changes in uirouter will be necessary. https://github.com/ui-router/angular/pull/544

Will report back after we upgraded our application

**Comment by christopherthielen** [comment]
Released as version `4.0.0`
