### ISSUE TITLE
How to handle fragments?

### ISSUE THREAD

**Issue by jelling** [ui-router/angular#62]
I'm using an authentication provider that redirects the user to http://localhost:3000/#access_token=2PBI2PLxD1as9sXo&expires_in=3600&{etc...}

How do I create a state that represents this? I've tried everything I can think of. With the stock router, people are subscribing to events like this:

```
  this
    .router
    .events
    .filter(event => event.constructor.name === 'NavigationStart')
    .filter(event => (/access_token|id_token|error/).test(event.url))
    .subscribe(() => {
      this.lock.resumeAuth(window.location.hash, (error, authResult) => {
        if (error) return console.log(error);
        localStorage.setItem('id_token', authResult.idToken);
        this.router.navigate(['/']);
      });
```

But I can't find a way in the docs to do something similar with ui-router-ng2.

**Comment by christopherthielen** [comment]
Can you try using an onBefore hook:

```
transitionService.onBefore({}, (trans: Transition) => {
  let urlService = trans.router.urlService;
  let stateService = trans.router.stateService;
  if (trans.$id === 0 && /^access_token/.exec(urlService.hash)) {
    ...
    return stateService.target('home');
  }
});
```

**Comment by jelling** [comment]
Thank you for the response and thank you for putting this together. It's a great tool.

I tried this code inside of an injected service and it didn't work there because the fragment is  stripped off by the time the service is loaded. I then moved the code to the root app component but there was no urlService object at trans.router.urlService. 

Long story short, I have fixed this by using window.location.hash.

**Comment by christopherthielen** [comment]
I'm surprised to hear that the fragment is stripped when the service is loaded but I'm glad that you found a solution.

For others coming here in the future, you can inject `UrlService` as a global service.  You can also perform before-app-start initialization starts using APP_INITIALIZER:

https://plnkr.co/edit/DaB16XdtXYOVjTKm9jAA?p=preview
