### ISSUE TITLE
Feature request: Allow state transition hooks to return observables

### ISSUE THREAD

**Issue by penfold** [ui-router/angular#639]
I can currently return a promise from a state transition hook.

https://ui-router.github.io/guide/transitionhooks#promises

In the new work of observables, it would be great if I could return an observable as my services all return them.

Thanks,
Paul

**Comment by wawyed** [comment]
You can easily convert an observable to a promise by using toPromise() so it shouldn't be a big deal to do so.

**Comment by christopherthielen** [comment]
yes, that's my recommendation as well.  transition hooks are a feature of ui-router core, which doesn't assume that rxjs is available.

**Comment by penfold** [comment]
That's a fair enough reason. Thanks for the feedback.
