### ISSUE TITLE
Project rename?

### ISSUE THREAD

**Issue by amcdnl** [ui-router/angular#64]
## Requirement
Project naming guides suggest dropping ng2 from project names. Given Angular4 is on the horizon, it might be time to adopt that pattern for this repo. No thoughts come to mind a better way to name this without it being confusing to others.

**Comment by christopherthielen** [comment]
I'm thinking @uirouter/angular for the npm package. Dunno about "friendly name" though.

**Comment by christopherthielen** [comment]
Closed by https://github.com/ui-router/angular/commit/61bd0565057f0f3be87ef4fa83cd6a62d1bc09b8

**Comment by amcdnl** [comment]
You forgot to rename the demo link `UI-Router for Angular: State-based routing for Angular (v2+) https://ui-router.github.io/ng2/`
