### ISSUE TITLE
UI Router + Ionic 4?

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [ui-router/angular#666]
Apparently new version of Ionic, instead of their own stack-based navigation, re-uses Angular Router. I'm not terribly familiar with the extend of this change, but I was wondering, if it could ever be replaced with UI Router, or is the integration too deep? I realize this is probably the wrong place to ask the question, but surely some UI Router users are asking themselves the same question?

I was okay with having Ionic navigation system in hybrid apps, but now I would have to work with Angular Router in one set of projects and UI Router in another set of projects, which is something I really would like to avoid, considering UI Router to be vastly superior.

**Comment by christopherthielen** [comment]
Sorry, I really don't know the answer to this.  I strongly suspect it's not feasible, but you'd have to ask the Ionic folks.
