### ISSUE TITLE
ERROR in Node does not exist

### ISSUE THREAD

**Issue by holuwaseun** [ui-router/angular#675]
Hi,

I just installed `@uirouter/angular` `v6.0.0` in my angular project that has `enableIvy` set to `true`. When I run `ng serve --prod` I get an error that says `ERROR in Node does not exist: C:/Projects/kos-ng IT konsults/Print Control/print-control-application/node_modules/@uirouter/angular`. I have attached an image of the error. Any help will be much appreciated.

![uirouter-error](https://user-images.githubusercontent.com/5493426/68741251-6d751880-05ed-11ea-9775-57733b0223f9.png)

Thanks

**Comment by wawyed** [comment]
Hi, as part of the release v6.0.0 or angular. The @uirouter/core and @uirouter/rx are now peerDependencies and need to be installed manually.

Have a look at https://github.com/ui-router/angular/blob/master/CHANGELOG.md#600-2019-11-12

**Comment by holuwaseun** [comment]
@wawyed Thanks... Installing the peerDependencies fixed it for me...

Cheers
