### ISSUE TITLE
Router resolves undefined values when building with "ng build --prod"

### ISSUE THREAD

**Issue by Humberd** [ui-router/angular#69]
## What is wrong?

I'm using @angular/cli and when I build a project using `ng build --prod` all the values that I resolve in all the states are returning undefined values. 

When I build using `ng serve` or `ng build` everything works fine.

## Steps to recreate

I created [this repo](https://github.com/Humberd/ui-router-resolve-undefined) that shows the problem.

I created a home component:
```typescript
@Component({
  moduleId: module.id,
  template: `Hello: {{foo}}`
})
export class HomeComponent implements OnInit {
  @Input() foo: string;

  constructor() {
  }

  ngOnInit() {
  }
}
```

In the `app.module` I created a default `home` state for that component:
```typescript
export function resolveFn() {
  return () => {
    return "bar";
  }
}

let state: Ng2StateDeclaration = {
  name: "home",
  url: "/home",
  component: HomeComponent,
  resolve: [{
    token: "foo",
    resolveFn: resolveFn
  }],

};

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    UIRouterModule.forRoot({
      states: [state],
      otherwise: "home"
    })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

In the `app.component.html` I added `ui-view` directive:
```html
<h1>
  APP COMPONENT
</h1>
<div ui-view></div>
```
### How does it look using `ng serve`
![image](https://cloud.githubusercontent.com/assets/10242142/24045443/6ec5a342-0b1f-11e7-83a7-860e293d32aa.png)

### How does it look using `ng build --prod`
![image](https://cloud.githubusercontent.com/assets/10242142/24045507/a743d5ae-0b1f-11e7-8c08-e030922731f5.png)

**Comment by marshall007** [comment]
@Humberd see #36. It's fixed in `1.0.0-beta.5` which hasn't been released yet. You'll need to use `@ResolveData()` instead of `@Input()` to decorate your input.

**Comment by aitboudad** [comment]
or just wait for angular 4 no need to use `@ResolveData()`, the only workaround right now is to downgrade the `@ngtools/webpack` version

**Comment by Humberd** [comment]
I updated the `@angular/cli` to the newest version `1.0.0-rc.2` and I can inject the input to the constructor like this:
```typescript
export class HomeComponent implements OnInit {
  constructor(@Inject("foo") private foo: string) {
  }

  ngOnInit() {
  }
}
```

**Comment by christopherthielen** [comment]
This should be working in latest ui-router using `@Input() foo: string;`, although injecting is also fine.
