### ISSUE TITLE
Implicit oauth redirect

### ISSUE THREAD

**Issue by naleon** [ui-router/angular#7]
I don't find any way to map url with the hash that come from an implicit oauth redirect,
ex: 
http://site.com/#access_token=9a885b89-a9b1-37c9-baa8-a321f83c07d3&token_type=Bearer&expires_in=961&session_state=8ae801dd4a90f6dada6f9af1779096c65b9b15e97661b18750edf134c0b9c7b2.maRdPLUgQesjZQiY-_F71Q

**Comment by christopherthielen** [comment]
Apologies for not responding sooner.

I'm very unfamiliar with oauth redirect.  Can you provide some context as to what you need to do?
You may be able to create [a custom URL Rule](https://ui-router.github.io/ng2/docs/latest/interfaces/url.urlrulesapi.html#rule) which handles something specific like this.
