### ISSUE TITLE
Lazy loading problem

### ISSUE THREAD

**Issue by mkoczorowski** [ui-router/angular#70]
Is the lazy loading only restricted to load modules inside the root component ? I have follower the setup described in the blog for beta4, created root config like so 
`export const NEW_CORE_ROUTES: Ng2StateDeclaration[] = [
  {
    name: 'test',
    url: '/routertest',
    component: HomeComponent
  },
  {
    name: 'test.**',
    url: '/test',
    loadChildren: '../modules/moozy/moozy.module#MoozyModule'
  }
]`

and then routing for the child
`export const MOOZY_ROUTES: Ng2StateDeclaration[] = [
  {
    name     : 'test',
    url      : '/test',
    component: MarcinComponent
  }
]`

in my case I have a 'core' module/folder and next to it 'modules/moozy'

overriding zombie.** as mentioned. It compiles fine (I'm using angular-cli) but when I go to /test
I got an exception regarding Dependency injection error, but it doesnt say what it tries to inject.
![image](https://cloud.githubusercontent.com/assets/8155896/24209089/2d50505e-0f1d-11e7-98c5-0a627b207d1c.png)

is there a plunkr with lazy loading working ?

**Comment by vshypivdych** [comment]
Works if use 
export function loadHomeModule() {
  return System.import('./home/home.module')
      .then(result => result.HomeModule);
}

Production STILL doesn't work
**TypeError: t.create is not a function**

**Comment by mkoczorowski** [comment]
Yeah, thanks but I'm trying to work with loadChildren syntax as it should be working form beta4 so its compatible with angular-cli. Now I'm getting an error:

![image](https://cloud.githubusercontent.com/assets/8155896/24315926/26a3774c-10e2-11e7-8c9b-fd3c49ddfbd1.png)

Would be great if we gat a plunker with this solution already working

**Comment by liangtongxie** [comment]
+1

**Comment by mkoczorowski** [comment]
I still cant get ui router to work with angular-cli build. the state url is being registered but the component (or lazy file) is not being loaded. Is there a plunkr with this working maybe ?

**Comment by paulodrade** [comment]
Same problem... :/
