### ISSUE TITLE
Force url to be lowercase?

### ISSUE THREAD

**Issue by JakeAi** [ui-router/angular#705]
Currently I'm using this in a routerConfigFunction. Is there a real method or better implementation than this?

```TS
import { Transition, TransitionService } from '@uirouter/core';

export function lowercaseUrlHook(transitionService: TransitionService) {
	transitionService.onCreate({}, (transition: Transition) => {
		if (location.pathname !== location.pathname.toLowerCase()) {
			transition.router.urlService.url(location.pathname.toLowerCase());
		}
	});
}

```

**Comment by njoel24** [comment]
Hi @christopherthielen 

uirouter should be able to expose an option to enable case-insensitive on query parameter and/or entire url . 

This seems to be solved for angularJS related as reported here: 
https://github.com/angular-ui/ui-router/issues/3379 

I tried looking for an option for the forRoot method in UIRouterModule but without success.

Is there any option we can use to achieve the above?

**Comment by JakeAi** [comment]
as annoying as it was to switch, I switched to angular router. Nothing in docs, or support forced me to switch.

**Comment by christopherthielen** [comment]
@njoel24 There is support in ui-router for making url matching case insensitive:

https://ui-router.github.io/ng2/docs/latest/classes/__uirouter_core_src_url_urlconfig_.urlconfig.html#caseinsensitive


```    UIRouterModule.forRoot({
      config: (router: UIRouter) => router.urlService.config.caseInsensitive(true)
    }),```

This only affects how the url is matched and does not force the URL to lowercase as in the original request.
