### ISSUE TITLE
UrlsService config strictMode won't propagate to UIRouterModule children?

### ISSUE THREAD

**Issue by stnor** [ui-router/angular#707]
I'm setting strict mode to false, but it does not seem to affect child modules (UIRouterModule.forChild()...

````javascript
export function routerConfig(router: UIRouter) {
    router.urlService.config.strictMode(false);
}

imports: [... UIRouterModule.forRoot({config: routerConfig, states: [])]
````

Hence I need to repeat the setting of strict mode in all child modules. A bit annoying. Bug or by design?

SO: https://stackoverflow.com/questions/59630354/ui-router-angular-2-set-strict-mode-false-for-all-modules

**Comment by christopherthielen** [comment]
That's not expected behavior, no.  The UrlService is a singleton on the router object, so the config should only need to be applied once.  Can you make a minimal reproduction of the issue?

**Comment by stnor** [comment]
I cannot reproduce it anymore.

It was a hybrid app Angular 1 / AngularJS 1.7.5 where I had the issue, and I notice now that the non-hybrid router removed the slash at the end in strict: false and the hybrid doesn't. Both work though.

I experienced that it did not work when using strict mode and a trailing slash. Got 404.

**Comment by christopherthielen** [comment]
ok, thanks for the follow up!
