### ISSUE TITLE
Use dynamically loaded component from module as component for state.

### ISSUE THREAD

**Issue by newmanw** [ui-router/angular#708]
I am currently trying to dynamically load an external module and then use a component that lives in that module as a component in a route which I am also defining at runtime.  In my case I would like for my main application to bootstrap the routes for my 'widgets' using components defined in these external widgets.

I am currently using SystemJS to pull the external module:

```
// Dynamic json config for widgets pulled from service
const widget = {
  url: 'http://widgets.com/widget-a.js',
  name: 'widget-a'
};

SystemJS.import(widget.url).then((module) => {
  const moduleFactory = this.compiler.compileModuleSync(module.default);
  const moduleRef = moduleFactory.create(this.injector);
  const widgets = moduleRef.injector.get('widgets');
  const resolver = moduleRef.componentFactoryResolver;
  const componentFactory = resolver.resolveComponentFactory(widgets[0][0].component)
  const component = componentFactory.create(this.injector) as Component;
});
```

At that point I have the component I would like to use in my new route:

```
this.stateRegistery.register({
  name: 'widgets.widgeta',
  url: '/widget-a',
  component: widgets[0][0].component,
});

```

However when doing this I get the following error:

> No component factory found for WidgetA.

Following this https://ui-router.github.io/guide/lazyloading#angular, I get that I am not loading a child module with future states.  However I don't really want my widgets to define their own states, in fact I don't really want widget providers to know anything about uirouter.

Is it possible to load a module dynamically and use a component within that module when defining a new route at runtime?

**Comment by newmanw** [comment]
Sorry, using ui-router-hybrid.  Should I move this ticket here: https://github.com/ui-router/angular-hybrid/?  Or is this something that applies to both projects.  In my particular case I am trying to dynamically load an angular module, not angularjs.

**Comment by christopherthielen** [comment]
@newmanw same question (as asked on the other issue you have open).  Are you still interested in a solution for this? 

I think the Ivy compiler in Angular v9 and v10 made general lazy loading of components much easier. It seems like the router shouldn't really get involved if I understand what you'd like to accomplish.
https://indepth.dev/lazy-loading-angular-modules-with-ivy/
