### ISSUE TITLE
Lazy loaded module future state routes are dependent on parent.

### ISSUE THREAD

**Issue by newmanw** [ui-router/angular#713]
Currently as outline in the LazyLoading documentation:
https://ui-router.github.io/guide/lazyloading#future-states

implemented here: 
https://github.com/ui-router/angular/blob/04c96790e5b2b558b8152b569c029c359a611920/src/lazyLoad/lazyLoadNgModule.ts#L177-L181

IE a future state defined in the parent

```
var contactsFutureState = {
  name: 'contacts.**',
  url: '/contacts',
  lazyLoad: function() {
    // lazy load the contacts module here
  }
}
```

Requires that this state named "contacts" is defined in the child module:

```
{
  parent: 'app',
  name: 'contacts',
  url: '/contacts',
  component: 'contactsComponent'
}
```

This becomes a problem when you don't want the lazily loaded child module to have to know where the parent is going to attach the state in the hierarchy.  For example in the case of a plugin architecture where plugins are written outside of a core application but different developers. In such a case an application might define that it wants route all "plugins" inside a parent "admin" state:

```
var plugin1FutureState = {
  name: 'admin.plugin1.**',
  url: '/plugin1',
  lazyLoad: function() {
    // lazy load the contacts module here
  }
}
```

This means that the plugin provider needs to know the root/parent state is "admin"
```
var plugin1State = {
  name: 'admin.plugin1',  <-- this creates tight coupling on the parent
  url: '/plugin1',
  component: Plugin1Component
}
```

If the main application decides to move all plugins to a new place:
```
var plugin1FutureState = {
  name: 'plugins.plugin1.**',
  url: '/plugin1',
  lazyLoad: function() {
    // lazy load the contacts module here
  }
}
```

Every plugin developer would need to modify their code to accommodate.

It would be nice to allow the parent/root to define where they want the child routes to lives.  From there the child routes should all be relative to the parents state.

```
var plugin1FutureState = {
  name: 'admin.plugin1.**',
  url: '/plugin1',
  lazyLoad: function() {
    // lazy load the contacts module here
  }
}
```

```
var plugin1State = {
  name: 'plugin1',
  url: '/',
  component: Plugin1Component
}
```

```
var plugin1State = {
  name: 'plugin1.options',
  url: '/options',
  component: Plugin1OptionsComponent
}
```

In this case the parent is registering a state that lives @ "plugins.plugins1", when loading plugins1, all states would be relative to "/plugin1".

> /admin/plugins1 -> Plugin1Component
> /admin/plugins1/options -> Plugin1OptionsComponent

From here the parent could make this move:

```
var plugin1FutureState = {
  name: 'plugins.plugin1.**',
  url: '/plugin1',
  lazyLoad: function() {
    // lazy load the contacts module here
  }
}
```

And the routes would now be mapped as the parent defined without any changes to the plugin modules

> /plugins/plugins1 -> Plugin1Component
> /plugins/plugins1/options -> Plugin1OptionsComponent

This relative mapping is how expressjs sub routers work.

**Comment by christopherthielen** [comment]
@newmanw are you still interested in a solution for this?  I think it's technically possible to accomplish your goal with ui-router, but you may need to jump through a few hoops first.  If you're still interested I will invest some time into explaining how.
