### ISSUE TITLE
prevent component destoy

### ISSUE THREAD

**Issue by mkoczorowski** [ui-router/angular#74]
Hi there,
Is there a way to prevent component from destroying when navigating? For example

I have two states, login and register. they both use the same component. which has another component as child. Both the same.
![image](https://cloud.githubusercontent.com/assets/8155896/24317290/a2cdc2d6-10ed-11e7-8852-458bf7615a2b.png)

when I navigate from one to another I would like the LoginComponent to stay and not be destroyed. Angular router has RouteReuseStrategy, is something like this possible using ui-router ?

Currently whenever I navigate from /login to /register Login Component gets destroyed. Is there a way to prevent this ?

![image](https://cloud.githubusercontent.com/assets/8155896/24317342/f3d21c86-10ed-11e7-84e8-b9b73148bf19.png)

I have always been a fan of ui router from angular 1, I would use this ng2 one for my new project

**Comment by christopherthielen** [comment]
No, sorry...  not in the way that you describe it.  When a state is activated, its views are instantiated.  When a state is exited, its views are destroyed.  However, maybe you could put the `LoginComponent` as the parent state component?

**Comment by mkoczorowski** [comment]
did that thanks
