### ISSUE TITLE
Catch-all parameter ignore link after '?' and '#'

### ISSUE THREAD

**Issue by Semigradsky** [ui-router/angular#765]
I use catch-all parameter but it ignores symbols after '?' and '#'.

My state:
```ts
const extState: Ng2StateDeclaration = {
  name: 'ext',
  url: '/ext/*path', // catch-all parameter
  dynamic: true,
  component: MyComponent,
}
```

My url: `http://localhost:4000/#/ext/foo?bar=1#/baz`

Actual result: `transition.params() === {path: "foo", #: "/baz"}`

Expected result: `transition.params() === {path: "foo?bar=1#/baz"}`

**Comment by christopherthielen** [comment]
That style of parameter `/*path` is only for the path portion, not for query parameters.  If you'd like access to the raw url, a workaround is to use the Angular `Location` API.  

There's a longtime feature request for wildcard query params, but it's never been implemented.
