### ISSUE TITLE
Create OnUiParamsChanged, OnUiExit interfaces instead of Ng2Component

### ISSUE THREAD

**Issue by stnor** [ui-router/angular#788]
It would be nice with separate interface exports for the hooks, and with a nice naming, such as:
```typescript
export interface MyComponent implements OnUiExit {
   uiCanExit(newTransition?: Transition): HookResult {
   }
}
```

As it is right now the NG2Component interface really does not add any declarative meaning for a person using the framework, imho:

```typescript
export interface MyComponent implements Ng2Component {
}
```

I don't get why a user-exposed interface has this design with all optional methods. I feel that its better to have one interface per hook and not use the optional (?) syntax.

```typescript
export interface Ng2Component extends Component {

   uiOnParamsChanged?(newParams: {
        [paramName: string]: any;
       }, trans?: Transition): void;

   uiCanExit?(newTransition?: Transition): HookResult;
}
```

Any chance of getting this? I could create my own interfaces, but feel it's better if it's in the framework. Thanks.

**Comment by christopherthielen** [comment]
That sounds good to me.  Would you like to take a shot at a PR?

**Comment by stnor** [comment]
Sure, I'll give it a try later this week.

**Comment by stnor** [comment]
@christopherthielen Should I remove, deprecate or leave "Ng2Component" as is?
It's only used internally in uiView.ts:214, so removing it makes sense to me, but that may obviously break some projects that use it.

**Comment by stnor** [comment]
PR #800
