### ISSUE TITLE
UIROUTER_MODULE_TOKEN is now a hidden export, but is required in external projects

### ISSUE THREAD

**Issue by euangoddard** [ui-router/angular#805]
Prior to version 6.0.2 `UIROUTER_MODULE_TOKEN` was an injection token that one could import outside the UI router project. Since this release, I get the follow error when trying to import:

```typescript
import { UIROUTER_MODULE_TOKEN } from '@uirouter/angular/injectionTokens';
```

Our application relies on this to do:

```typescript
{ provide: UIROUTER_MODULE_TOKEN, useFactory: STATES_MODULE_FACTORY, deps: [TRANSFORMED_STATES], multi: true },
``` 

Could you please allow this token to be imported by external applications again?

**Comment by mkoczorowski** [comment]
+1

**Comment by christopherthielen** [comment]
I'm re-exporting these in #810 
Note that these tokens are marked as @hidden and are considered internal implementation details, not public API.  Use at your own risk.

**Comment by euangoddard** [comment]
@christopherthielen many thanks. Do you have a time-frame for a release to that incorporates this change?

**Comment by christopherthielen** [comment]
https://github.com/ui-router/angular/releases/tag/6.0.3
