### ISSUE TITLE
Query parameter not allowing array with single item

### ISSUE THREAD

**Issue by dimmreaper** [ui-router/angular#829]
_I've previously posted [this question on StackOverflow](https://stackoverflow.com/q/62640754/3123195) as well. I'd call this a bug in UI Router, except that it seems like such a normal situation that the problem must be me (but I don't see how.)_

I have an application using UI-Router. There is a Widgets state with one query parameter that accepts an array of widgets:

    const widgetsState = { name: "widgets", url: "/widgets?{widgets:string[]}", component: Widgets, params: {
      widgets: {
        isArray: true,
        value: [],
      }
    } };
Routing to this state works with an empty array or an array with multiple items, but fails when given an array of just one item:

    <a uiSref="widgets" [uiParams]="{ widgets: [] }">Empty array - works fine</a>
    <a uiSref="widgets" [uiParams]="{ widgets: ['foo'] }">Single item - throws error!</a>
    <a uiSref="widgets" [uiParams]="{ widgets: ['foo','bar'] }">Multiple items - works fine</a>
When routing with just a single item in the array, I get this error:

This transition is invalid, detail: The following parameter values are not valid for state 'widgets': [widgets:"foo"]))

**How can I get UI-Router to allow an array containing a single item to be passed in as a parameter?**

[This Stackblitz demo](https://stackblitz.com/edit/uirouter-angular-hello-world-nwxubm) shows a minimal reproduction of the error.

I've noticed that if I remove the parameter from the url, it will properly handle arrays of single items. However I need to retain the ability to deep-link with these parameters, so that's not an option for my application.

I experienced this with @ui-router/angular version 5, but also see the same behavior in versions 6 and 7.

**Comment by christopherthielen** [comment]
Here's a fork of your stackblitz: https://stackblitz.com/edit/uirouter-angular-hello-world-zzt9u6

I changed your widgets stage to:
```ts
const widgetsState = {
  name: "widgets",
  url: "/widgets?{widgets}",
  component: Widgets,
  params: {
    widgets: {
      type: "string",
      array: true,
      value: []
    }
  }
};
```

Note: `array: true`, not `isArray: true`

**Comment by dimmreaper** [comment]
Doh! Thanks, @christopherthielen! I'd read the docs but still somehow missed it. If you want to post a quick answer on SO as well, I'll accept it.

Thanks for all you do with UI-Router!
