### ISSUE TITLE
appcomponent instantiate twice

### ISSUE THREAD

**Issue by liangtongxie** [ui-router/angular#83]
```
imports: [
        BrowserModule,
        HttpModule,
        FormsModule,
        ReactiveFormsModule,
        UIRouterModule.forRoot({
            states:appRoutes,
            otherwise: { state: 'app.home', params: {} },
            useHash: false
        }),
        HomeModule,
        // routing,
        SharedModule
    ],
    declarations: [
        AppComponent
    ],
bootstrap: [ AppComponent ]
```

I use the version 1.0.0-beta.4, when I started app , appcomponent was instantiate twice ...

![qq 20170406140825](https://cloud.githubusercontent.com/assets/16974453/24740454/de1031f4-1ad3-11e7-8491-1d1e35669f46.png)

**Comment by christopherthielen** [comment]
Is this still an issue?  I need to see a reproduction of the problem to offer any help.  

If you can reproduce it (for example using [stackblitz](https://stackblitz.com/ui-router-angular)) I'd be happy to help.  Closing for now, please reopen if this is still an issue for you.
