### ISSUE TITLE
disguiseToken undefined

### ISSUE THREAD

**Issue by jobejas** [ui-router/angular#848]
There's  existing [discussion in stackoverflow](https://stackoverflow.com/questions/55193973/cannot-read-property-disguisetoken-of-undefined) regarding this issue. I'm just wondering if anyone might know anything about this.

I encountered after adding lazyloading to the app if that's something makes sense related to this issue.
My app is currently in hybrid. Angular v10 + angularjs 1.8.0

TypeError Cannot read property 'disguiseToken' of undefined 
    :1:40912:24 getOwnPropertyDescriptor
    codebuild/output/src918382939/src/public/build/node_modules/zone.js/dist/zone.js:2628:23 Function.Object.getOwnPropertyDescriptor
    codebuild/output/src918382939/src/public/build/node_modules/tslib/tslib.es6.js:54:81 __decorate
    codebuild/output/src918382939/src/public/build/ng:/@uirouter/angular/directives/uiView.ts:127:2 Module../node_modules/@uirouter/angular/__ivy_ngcc__/fesm2015/uirouter-angular.js

**Comment by christopherthielen** [comment]
I've never seen this error before, and 'disguise' is not in the ui-router codebase.    My suspicion is that it's related to __decorate and zone.js.
