### ISSUE TITLE
Latest documentation broken

### ISSUE THREAD

**Issue by dimmreaper** [ui-router/angular#854]
The documentation at https://ui-router.github.io/ng2/docs/latest/ appears to be broken for the current and last few versions. The links in the menu on the right are not clickable, and searching for something (e.g., StateService) finds nothing. If I change the dropdown to view documentation for 6.0.0 or older, the menu loads and is clickable and searching works as expected.

**Comment by christopherthielen** [comment]
fixed the 404 links, but the search remains broken for now (I won't have time to investigate the search right now, I hope having the major components always navigable will mitigate this problem)
