### ISSUE TITLE
Components recreated on navigation

### ISSUE THREAD

**Issue by vinaysoni** [ui-router/angular#86]
Hi,
I was playing with this plunker and added a constructor to person.ts, people.ts, about.ts to show an alert whenever constructor is invoked. 

https://plnkr.co/edit/1wB5QZSPvvCJZXBWMLXU?p=preview

I notice that whenever I re-navigate to a link, the component is recreated.

If I am entering data on a Form and decide to navigate to another link, to obtain some related information to complete the form, when I come back, the form would be wiped out.

Same will happen on a search. Say, I display some search results on about, then go to people and come back, I will have to fetch the results again to display the results on about page.

My question is why are we destroying objects and recreating them on renavigation? There is valuable information in that object that may not have made way to its model or persistent state.

I recall that in ui-router 1 demo I was able to change the phone numbers, or email address and when I came back to it, my changes would always be there.

Thanks.

**Comment by vinaysoni** [comment]
In angular2 latest router, I believe they help you to retain components via RouteReuseStrategy . I would love to see a way to do the same in ui-router.

**Comment by christopherthielen** [comment]
I'm not sure I understand.  When you route away from a state and its component is no longer being rendered, then it must be re-created when the state is reactivated.

There is a possibility of supporting component reuse if *only the parameters are changing*.  Instead of reloading the entire state, the component could be fed the updated data as inputs.

**Comment by vinaysoni** [comment]
But why destroy the component in the first place when someone navigates away from the route and recreate it ? This is unnecessary if user navigated just to get some information from another route. The component could be cached and reused if the developer gives a que to router. That is what Route reuse strategy is all about in latest ng2 router. It has nothing to do with parameters changing on the same component. In fact Java swing and most other frameworks retain components forever. 
If the same component is navigated to  again it can be retrieved from cache and the developer doesn't have to maintain state explicitly which can be really hard in many scenarios.
