### ISSUE TITLE
Inconsistent encoding and decoding of string array params

### ISSUE THREAD

**Issue by danhooper** [ui-router/angular#867]
When a parameter is defined as an array and a string depending on the number of items in the array the strings within the list may be encoded or may not be.

See https://stackblitz.com/edit/uirouter-angular-string-array for a stackblitz that replicates the issue.

I think all of the string parameters should be URL encoded/decoded.

When there is a single item the items are URL encoded/decoded properly. When there is more than one item, none are URL encoded/decoded.

This may be a similar issue as https://github.com/ui-router/core/issues/534 and https://github.com/ui-router/angular/issues/340

**Comment by christopherthielen** [comment]
Was this a regression?

**Comment by christopherthielen** [comment]
Not a regression.   I'm shocked this bug has existed for this long, thanks for the nice reproduction.

**Comment by danhooper** [comment]
Thanks for the great library, we've been using it on one of my projects for probably 5 years across AngularJS to a hybrid app and now just Angular.
