### ISSUE TITLE
ng build --prod

### ISSUE THREAD

**Issue by jmls** [ui-router/angular#87]
when trying to build, I get the error

`ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable `

this using `"ui-router-ng2": "ui-router/ng2#angular4-artifacts",`

angular-cli 1.0.0
@angular/core 4.0.2

**Comment by zhongsigang** [comment]
ng build -prod, it shows the following error message,
emittingUnhandled rejection Error: ENOENT: no such file or directory, open 'C:\xxx\node_modules\_@uirouter_core@5.0.11@@uirouter\package.json'

    "@angular/cli": "^1.5.4",
    "@angular/animations": "5.0.3",
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
...

**Comment by christopherthielen** [comment]
@jmls I assume this is no longer an issue with more recent versions of angular/cli and ui-router?  Let me know if that's not the case.

@zhongsigang please open a new issue with details on how to reproduce the error.
