### ISSUE TITLE
Build error: Only initialized variables and constants can be referenced

### ISSUE THREAD

**Issue by isherwood** [ui-router/angular#88]
My app was originally built with ng2.x and the current CLI at that time. I'm now trying to build with ng4.0.2 and CLI 1.0.0. It's fairly simple, with just a few root-level routes. Here's an abbreviated look:

```
export let typographyState: Ng2StateDeclaration = {
    name: 'typographyState',
    component: TypographyComponent,
    url: '/typography'
}

export let routerConfig = {
    otherwise: '/',
    states: [
        typographyState
    ],
    useHash: false
};

@NgModule({
    declarations: [
        AppComponent,
        TypographyComponent
    ],
    imports: [
        BrowserModule,
        FormsModule,
        HttpModule,
        MaterialModule.forRoot(),
        FlexLayoutModule,
        UIRouterModule.forRoot(routerConfig)
    ],
    providers: [],
    bootstrap: [AppComponent]
})
export class AppModule { }
```
I get this error on build (ng build --prod):

> ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 15:22 in the original .ts file), resolving symbol ROUTES in /path/node_modules/@angular/router/src/router_config_loader.d.ts, resolving symbol makeRootProviders in /path/node_modules/ui-router-ng2/lib/uiRouterNgModule.d.ts, resolving symbol UIRouterModule.forRoot in /path/node_modules/ui-router-ng2/lib/uiRouterNgModule.d.ts, resolving symbol AppModule in /path/src/app/app.module.ts, resolving symbol AppModule in /path/src/app/app.module.ts

> ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/path/src'
 @ ./src/main.ts 5:0-74
 @ multi ./src/main.ts

I suspect that the second error is a result of the first. If I do a dev build (ng build), this warning is added at the beginning:

> WARNING in ./~/ui-router-ng2/lib/private_import_core.js
9:23-24 "export '__core_private__' (imported as 'r') was not found in '@angular/core'

**Comment by christopherthielen** [comment]
Did you use the beta.4 version? It doesn't support angular 4.x

I've released beta.5 which also supports only angular 2.x.  Beta.6 is just around the corner and should solve this issue.

**Comment by isherwood** [comment]
Thank you. I suspected that I was ahead of the curve a bit and resorted to using core routing for now. I appreciate your work on this.

**Comment by christopherthielen** [comment]
beta.6 is released
