### ISSUE TITLE
NoProviderError (Resolve)

### ISSUE THREAD

**Issue by SergeyJyravlev** [ui-router/angular#91]
Hello. 
``export const states: Ng2StateDeclaration[] = [
  {
    name: 'login',
    url: '/login',
    component: LoginComponent,
    resolve: [
      {
        token: 'user',
        deps: [UserService],
        resolveFn: (userSvc) => userSvc.checkAuth()
      }
    ]
  }
];``

import {UIRouterModule, Ng2StateDeclaration} from "ui-router-ng2";
import {LoginComponent} from "../components/login/login.component";
import {UserService} from "../services/UserService";

And i get the error.

![2017-04-19 17 58 48](https://cloud.githubusercontent.com/assets/20172061/25186796/e64c7a34-2529-11e7-998a-e4b8fb511cc2.png)

Please can help me.

**Comment by SergeyJyravlev** [comment]
Used TypeScript 2.1.6

**Comment by christopherthielen** [comment]
hi @SergeyJyravlev 
There's not enough information provided to tell what's wrong.  Note that ui-router doesn't have a symbol named `Resolve`.

Can you provide a reproduction of some sort?
