### ISSUE TITLE
uiSref doesn't work unless matching "name". Can't use full path/name.

### ISSUE THREAD

**Issue by stnor** [ui-router/angular#945]
I have a hierarchy in my app with loads of states, of which some are lazy.
Example:
<img width="984" alt="Screenshot 2021-08-30 at 12 57 49" src="https://user-images.githubusercontent.com/561167/131329338-6f2ce7e9-a2eb-4c61-98a7-bc053db0f6e2.png">

My expectation is that uiSref="plus.mentees.current.mentee.dashboard" would work, but only "mentee.dashboard" works (since that's the 'name' of the state). Shouldn't fully qualified state paths work in uiSref?

Thanks in advance.

**Comment by christopherthielen** [comment]
Hi, yes it's expected that fully qualified state name `plus.mentees.current.mentee.dashboard` should work.  It's also surprising that `mentee.dashboard` works (it's not expected)

**Comment by stnor** [comment]
Yeah, it's weird. Nothing happens when navigating/clicking and there are no errors. I've since migrated to the Angular Router,  but migration would have been a total PITA without this project. Thanks for all your work!
