### ISSUE TITLE
How to lazy load with chunks

### ISSUE THREAD

**Issue by Lubjan** [ui-router/angular#947]
Hello,

I've been using ui-router since AngularJS, but I've never really felt the need to lazy-load modules until now, as performance is a major point for a project I'm working on. I've come into contact with the lazy-load mechanism of the default Angular Router before, but generally don't like the default router, so I'd prefer to stay with ui-router.

My problem is that with the ui-router lazy loading, Angular doesn't seem to generate separate chunks for lazy loaded modules, resulting in no size difference of the initial chunk.
I've been following the guide for Angular (https://ui-router.github.io/guide/lazyloading#angular) and adjusted my code accordingly (see example module below).

***media-player.module.ts***
```typescript
...
@NgModule({ 
  declarations: [...],
  imports: [
    SharedModule,
    UIRouterModule.forChild({
      states: [{
        name: 'mediaPlayer',
        url: '/player/:id',
        component: MediaPlayerComponent,
      }],
    }),
  ];
})
export class MediaPlayerModule { }
```

***app.module.ts***
```typescript
...
@NgModule({
  declarations: [...],
  imports: [
    UIRouterModule.forRoot({
      states: [
        ...,
        {
          name: 'mediaPlayer.**',
          loadChildren: async () => import('./modules/media-player/media-player.module').then((m) => m.MediaPlayerModule),
        },
        ...,
      ],
      initial: ...,
      otherwise: ...,
      config: ...,
    }),
  ],
  providers: [...],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

**Comment by mokipedia** [comment]
Hi @Lubjan,
there is a lot missing here -  like: do you use angular cli or custom build config?

as long as you do not import the module into the root module, the cli build generates a chunkfile that is then lazyloaded automatically by the code you shared.

This is not a problem with ui-router btw but most likely with your code or setup. My first guess would be you still import the media player module somewhere so the bundler sees no benefit in chunking it out.

**Comment by Lubjan** [comment]
Hey,
just sorry for the forgotten information there, I use the default CLI no custom configuration.

As you pointed out, I did indeed forget to remove the MediaPlayerModule (and others) from the app.module.ts, resulting in no generated chunks. Removing them now generates the chunks. 

But now it won't let me navigate to any routes of lazy modules, gotta figure out why.

**Comment by Lubjan** [comment]
Okay I've added the url
```diff
{
  name: 'mediaPlayerModule.**',
+ url: '/watch',
  loadChildren: async () => import('./modules/media-player/media-player.module').then((m) => m.MediaPlayerModule),
},
```
and adjusted the children accordingly
```diff
export const states: Ng2StateDeclaration[] = [
  {
    name: 'mediaPlayerModule',
    abstract: true,
  },
  {
    name: 'stream',
-   url: '/stream/:id?t',
+   url: '/watch/stream/:id?t',
    component: MediaPlayerComponent,
    params: {
      t: {
        type: 'int',
        inherit: false,
      },
    },
    resolve: {
      info: [
        ApiService, Transition,
        async (api: ApiService, trans: Transition) => api.mediaInfo({ episode: trans.params().id }).toPromise(),
      ],
      playlist: [
        ApiService, Transition,
        async (api: ApiService, trans: Transition) => api.mediaPlaylist({ episode: trans.params().id }).toPromise(),
      ],
      discoverySimilar: [
        ApiService, Transition,
        async (api: ApiService, trans: Transition) => api.discoverySimilar().toPromise(),
      ],
    },
    data: { enabled: environment.modules.streams },
  },
];
```

Navigating to `localhost:4200/watch/stream/<id>` works fine, but when used as a link (e.g. `<a uiSref="stream" [uiParams]="{id:519}">stream</a>`) it won't navigate, only after a link with `uiSref="mediaPlayer.mediaPlayer"` is clicked it will resolve them. I feel extremely dumb right now.

Any idea where my problem could lie?

**Comment by mokipedia** [comment]
I would argue that `stream` is not a child of `mediaPlayerModule`.
Eigher call it `mediaPlayerModule.stream` or set `parent: 'mediaPlayerModule'`.
Not sure why you use that abstract though. seems unnecessary if you only have 1 route.

In general: `mediaPlayerModule.**` means als children of mediaPlayerModule (including itself) are to be found in this lazy chunk.

**Comment by Lubjan** [comment]
I also tried `mediaPlayerModule.stream` before but with the same result, only difference being that there was no component loaded when navigated directly to (resolvers did load though).
There are other sub-routes planned, that's why stream is a separate child of `mediaPlayerModule` and itself being abstract.

**Comment by mokipedia** [comment]
have you tried adding a layout view (can be an empty component with `<div ui-view></div>` to your abstract? I have to admit I have not tried an abstract state without view.

**Comment by Lubjan** [comment]
> have you tried adding a layout view (can be an empty component with `<div ui-view></div>`) to your abstract? I have to admit I have not tried an abstract state without view.

That fixed the view being empty, but the links can still not be navigated to unless the link to the parent is used once.
![](https://i.imgur.com/mhjNQ9Z.gif)

Is there by any chance a setting (that I may have overlooked) to tell UI router to load lazy modules as soon as the initial chunk finished loading like in Angulars `preloadingStrategy` for the default router. But I guess the problem would still stand for users with slow connections.

**Comment by mokipedia** [comment]
As I said, they need to be nested. There is no `stream` state in root.
You tell root all there is, but a future state indicates, there is more nested here with this name after lazyloading.
`mediaPlayerModule.stream` is the identifyer coming from root, however you have to tell him in the state (by naming it like that or by adding the parent, as I stated before). Navigation via URL works, as you tell him to look into all states after loading that module in `/watch` and there is a state that matches the given url in there. however it is not a child of abstract `mediaPlayerModule`

**Comment by Lubjan** [comment]
Okay, changed it to that now the link works on click (had `mediaPlayerModule` set as `parent` before), thanks for the help on that. :D
But I noticed a small thing that could still be a problem, when the module is not yet loaded any link that would navigate to `/watch/stream/<id>` just links to `/watch` is that still something that occurs because I have incorrectly set things up or is that normal and I should just generate a static link from it as placeholder?

**Comment by mokipedia** [comment]
As the module holds the state definitions, I think that is normal. You can however (and I would encourage you to) split the lazyloaded routes each into a future state to minimize the chunk size and give the future state a full url description. that way the url is always known, even when the state itselt if not.

**Comment by Lubjan** [comment]
Okay will do that, thank you very much for your help.
Hope you have a pleasant Tuesday :)
