### ISSUE TITLE
Incompatibility with Angular v13 - removal of `NgModuleFactoryLoader`

### ISSUE THREAD

**Issue by gkalpak** [ui-router/angular#949]
FYI, the deprecated `NgModuleFactoryLoader` has been recently removed from `@angular/core` (angular/angular@361273fad5030c900c83d333a779f6edbe20c688). This change will land in v13.

This breaks `@uirouter/angular` because it imports it here: https://github.com/ui-router/angular/blob/9d88213ec9a1929289349506ac6d2c26f84ece31/src/lazyLoad/lazyLoadNgModule.ts#L1

I am not sure what would be the best way forward to address this in `@uirouter/angular`, but I just wanted to raise awareness.

**Comment by DOrlov77** [comment]
Hello, Angular 13 is here...
Any porgress so far?
