### ISSUE TITLE
error 'No provider for Transition' in unit testing

### ISSUE THREAD

**Issue by simonzhlx** [ui-router/angular#96]
Hi Guys,

I'm using ui-router-ng2 in my ng2 project. And the UIRouterModule is imported with function forRoot invoked.
All things went well except one of my unit test suites for testing a component that had the dependency of Transition in order to obtain parameters from query strings. I setup the testing module by leveraging my AppModule due to many dependencies declared in AppModule. And getting the error as title says each time running the test suite mentioned above.
Here's the pseudo code of the test suite:

```import {APP_BASE_HREF} from "@angular/common";
import {TestBed, async, inject} from "@angular/core/testing";
import {AppModule} from "../index";
import {Observable} from "rxjs";
import {StateService, Transition} from "ui-router-ng2";
import {XXComponent} from "./XXX.component";
describe('XXComponent', () => {
beforeEach(async(() => {
TestBed.configureTestingModule({
providers: [
{provide: APP_BASE_HREF, useValue: '/'}
],
imports: [
AppModule
]
});
TestBed.compileComponents();
}));

it('should complete XXX', async(inject(
[StateService, Transition, XXComponent], (service, transition, component) => {
let oId="823";
let aId ="123";
spyOn(transition, 'params').and.returnValue({'oId': '823', 'aId': '123'});
spyOn(stateService, 'go').and.stub();
... })));
})
```

I tried to put Transition to Testing Module as a provider which caused another error:

Can not resolve all prameters for Transition (?,?,?)
Another thing made me confused that I can not find any factory for Transition after going through the source of ui-router/angular. In my understanding, there should be a factory for Transition exported by UIRouterModule(how come my component got the instances of Transition via DI mechanism?).

**Comment by christopherthielen** [comment]
Transition can't be injected from the root injector because it's not a global service.  A unique Transition object is created for each state change (transition).  Each transition actually has an auto-increment identifier (`transition.$id`).

The transition can be injected into a routed component because UI-Router creates a child injector before creating the component.  We add the Transition to the child injector, as a provider.  However, this happens *in response to* a `state.go`.

You won't be able to mock the Transition in the way you've pasted.

**Comment by kotmatpockuh** [comment]
@christopherthielen how to get params then?

**Comment by christopherthielen** [comment]
there are a couple options.  
1) Listen for transitions using a transition hook, for example
2) use the `UIRouter.globals.params`

**Comment by simonzhlx** [comment]
@kotmatpockuh params also can be fetched from StateService.
@christopherthielen thanks for your reply. The point of my thread was to figure out a way to unit test the components that have dependency with Transition(in other word the constructor of those components get a parameter of Transition). Could you show me code snippets to do it?

**Comment by siddhartha-gupta** [comment]
@simonzhlx I resolved it with the following code. Please let me know in case you come up with some better solution

describe('CustomComponent', () => {
    let fixture: ComponentFixture<CustomComponent>;
    let app: CustomComponent;

    beforeEach(() => {
        TestBed.configureTestingModule({
            imports: [
                // Your import goes in here....
            ],
            declarations: [
                // Declare your component
                CustomComponent
            ],
            providers: [
                // Mention your providers in here
                // provide the Transition param here
                // i.e, for transition.params().id
                {
                    provide: Transition, useValue: {
                        params: function() {
                            return {
                                id: 'awesome-id'
                            };
                        }
                    }
                }
            ],
        }).compileComponents();

        fixture = TestBed.createComponent(CustomComponent);
        app = fixture.componentInstance;
    });

    it('should create the app', () => {
        expect(app).toBeTruthy();
    });
});
