### ISSUE TITLE
Angular 15 support

### ISSUE THREAD

**Issue by jonathanford** [ui-router/angular#972]
We are using ui-router with a hybrid application and just wanted to check if Angular 15 support is on the roadmap?

Many thanks

**Comment by msgoloborodov** [comment]
I created PR to try to do this: https://github.com/ui-router/angular/pull/973

**Comment by StepaZol** [comment]
why are you using it? the default routing module in angular can do everything this library can and more. at the same time, there is no need to keep the dependency and wait for an update for compatibility.

**Comment by msgoloborodov** [comment]
> why are you using it? the default routing module in angular can do everything this library can and more. at the same time, there is no need to keep the dependency and wait for an update for compatibility.
> maybe I don't understand something. can you explain to me?
We had angular.js project with ui-router and then we had migrated to Angular. We are planning to migrate to angular native router, but project is very large and it is not so easy.

**Comment by jonathanford** [comment]
We also have legacy code from an AngularJS project and routing is probably going to be the last thing we can migrate. Using @uirouter/angular-hybrid package works well in the meantime, ideally with support for the latest Angular version.

**Comment by wawyed** [comment]
New version has been released to support Angular 15.  uirouter/angular-hybrid wil be updated soon as well.
