### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by davidgronlund** [ui-router/angular#984]
ui-router seem to work fine with Angular 16. However, the peer dependency against Angular 15 breaks the npm install process. It can be overridden using `--force` or `--legacy-peer-deps`, but that feels too hacky for production. We are in the process of migrating to Angulars built in routing, but are not done yet. Would it be possible to bump the versions?

Thanks!

**Comment by davidgronlund** [comment]
For those who might face the same problem. We managed to resolve the depency issue by using npm overrides.

At root level in `package.json` we added this:

```
"overrides": {
    "@uirouter/angular": {
      "@angular/common": "^16.0.0",
      "@angular/core": "^16.0.0"
    }
}
```

**Comment by 2advancesolutions** [comment]
Do anyone plan on fixing the to make it stable with angular 15 and 16 without doing a hack work around. Reason I ask is because most of the docs are outdated and I don't see a passing build. Is this safe to use for production ?

**Comment by wawyed** [comment]
You shouldn't have any issues running angular 15 ?

**Comment by 2advancesolutions** [comment]
@wawyed  I ran into issue thanks for response when creating a empty angular 15 project and adding UI router and then trying to do ng serve I errors trying to build UI router. Can you share a repo with empty angular 15 project with 1 route to demo that it's working ?  I don't think UI Router is support in 15 and 16 look at the old demos there all in angular 9 and 10 which is outdate now

**Comment by 2advancesolutions** [comment]
``
![UI-Router](https://github.com/ui-router/angular/assets/7279973/46bb3149-7a57-4ef6-9a62-919a8eb3b5c2)

**Comment by 2advancesolutions** [comment]
![UIRouterBuild](https://github.com/ui-router/angular/assets/7279973/b27b099f-88ee-4fd4-90d9-df28bc8e7ffa)

**Comment by wawyed** [comment]
> @wawyed I ran into issue thanks for response when creating a empty angular 15 project and adding UI router and then trying to do ng serve I got errors trying to build UI project. Can you share a repo with empty angular 15 project with UI route to demo that it's working ? I don't think UI Router is support in 15 and 16 and I look at the old demos using UI router there all in angular 9 and 10 which is outdate now

https://github.com/ui-router/sample-app-angular This should be using angular 15

**Comment by davidgronlund** [comment]
We have now migrated to `@angular/routing`. Not gonna lie, it was a hassle in some cases. The main issue, as far as my understanding goes, is that `ui-router` is not reusing components, while `@angular/routing` do for performance. This created major issues in instances where reloading and switching routes depended on `ngOnInit` being called again. There were ways around this, but it was not easy. Custom route resuse strategies where part of the solution but not completely.

**Comment by wawyed** [comment]
Version 12 is out with angular 16 support
