### ISSUE TITLE
Angular 18

### ISSUE THREAD

**Issue by dmytro-kuz** [ui-router/angular#992]
I am upgrading the project to Angular 18 and would love it if you could release a new version with v18 support!

**Comment by wawyed** [comment]
My time is limited on this project but feel free to submit a PR if you wish!

**Comment by lukaVarga** [comment]
@wawyed here are the PRs for angular 18 support for the relevant projects:
- https://github.com/ui-router/angular/pull/993
- https://github.com/ui-router/angular-hybrid/pull/598
- https://github.com/ui-router/sample-app-angular/pull/789
- https://github.com/ui-router/sample-app-angular-hybrid/pull/918

Please let me know if anything else is needed

**Comment by wawyed** [comment]
All done! Thank you for the help :)
